## Following kernels will load source name text files into a filtered ARCHS4 database

### Function to load sample names from text file

In [1]:
import glob
import sys
import h5py
import archs4py as a4
import re
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
def load_sample_names(txt_file_path):
    """Load sample names from a text file"""
    with open(txt_file_path, 'r') as f:
        sample_names = [line.strip() for line in f if line.strip()]
    return sample_names

In [4]:
%cd /scratch/by2372/pipeline/ARCHS4_Macrophages/Source_name_4_class/
class_sample_dict = dict()

# loop through all file paths in current directory to find files of interest
for filename in glob.glob("*3.txt"):
    file_path = "/scratch/by2372/pipeline/ARCHS4_Macrophages/Source_name_4_class/" + filename
    # sample_names are within the text files and are the values of the class_sample_dict
    sample_names = load_sample_names(file_path)
    # class names are within the names of the text files
    class_name = filename.replace("3.txt","")

    class_sample_dict[class_name] = sample_names

/scratch/by2372/pipeline/ARCHS4_Macrophages/Source_name_4_class

In [5]:
class_sample_dict

{'Macrophage': ['PCA-ASSOCIATED CD14+CD11B+ MACROPHAGES',
  'WT ESC-DERIVED MACROPHAGE',
  'PERIPHERAL BLOOD MONOCYTE-DERIVED MACROPHAGES',
  'PRIMARY MACROPHAGE',
  'PRIMARY HUMAN MONOCYTE-DERIVED MACROPHAGES, ADMAF, IFN-Î³',
  'MACROPHAGE WITH CONTROL LNA 24H_REP#2',
  'MACROPHAGE_6D_MEDIA_MTB_4H',
  'PRIMARY HUMAN MACROPHAGE CELLS',
  'H1 ESC-DERIVED M1 MACROPHAGES',
  'MACROPHAGES(BC9)',
  'HUMAN MONOCYTE-DERIVED MACROPHAGE',
  'ACTIVATED MONOCYTE-DERIVED MACROPHAGES',
  'PERIPHERAL_BLOOD_MACROPHAGE-M0_SICTRL',
  'IPSC-DERIVED M0 MACROPHAGE',
  'HU-CB-MACROPHAGE-RNA, WT-CB',
  'BONE MARROW DERIVED MACROPHAGE',
  'HUMAN HEALTHY BLOOD DONOR MONOCYTES-DERIVED MACROPHAGES',
  'MACROPHAGES',
  'MONOCYTE-DERIVED MACROPHAGES, SSC',
  'PERIPHERAL BLOOD MONOCYTE-DERIVED MACROPHAGES NATURAL',
  'MACROPHAGE IN NORMOXIA 48H',
  'RNA FROM MONOCYTE-DERIVED MACROPHAGES 4 HOURS AFTER CULTURED WITHOUT VIRUS',
  'HUMAN IPSCS-DERIVED MACROPHAGES',
  'PRIMARY HUMAN MONOCYTE-DERIVED MACROPHAGES',
  'HUMAN MACROPHAGES (MO-GMCSF)',
  'PLEURAL MACROPHAGES',
  'MACROPHAGES(BC12)',
  'MONOCYTE-DERIVED MACROPHAGE',
  'MACROPHAGES(BC11)',
  'MONOCYTES-DERIVED MACROPHAGES',
  'MACROPHAGE IN NORMOXIA 24H',
  'DIFFERENTIATED MACROPHAGE',
  'BLOOD MONOCYTE DERIVED M1 MACROPHAGE',
  'HUMAN IPSC-DERIVED CAR-MACROPHAGE',
  'HU-IPSC-MACROPHAGE-RNA, WAS-C',
  'PBMC DERIVED MACROPHAGE (HMDM)',
  'PRIMARY MACROPHAGE CELLS',
  'MONOCYTE DIFFERENTIATED TO MACROPHAGES WITH PMA',
  'SORTED BONE MARROW MACROPHAGES',
  'M0 MACROPHAGES DIFFERENTIATED FROM PRIMARY PBMCS',
  'MONOCYTE-DERIVED MACROPHAGES, CONTROL',
  'MACROPHAGE 2 CONTROL REPLICATE 4',
  'SORTED AFHI CD206+ CD45+ MACROPHAGES FROM BALF',
  'MACROPHAGES FOLR2 POS',
  'IPSC DERIVED MACROPHAGE',
  'INTESTINAL MACROPHAGES',
  'CONTROL MACROPHAGES',
  'BLOOD MONOCYTE DERIVED M0 MACROPHAGE',
  'M1 MACROPHAGES',
  'MACROPHAGES, HEALTHY',
  'HUVEC+DPSC+CARDIOMYOCYTES+MACROPHAGES',
  'PRIMARY HUMAN MONOCYTE-DERIVED MACROPHAGES, SICTRL',
  'MACROPHAGE WITH CONTROL LNA 24H',
  'HUMAN PBMC DERIVED MACROPHAGES',
  'M2 MACROPHAGE',
  'MONOCYTO-DERIVED MACROPHAGES',
  'MACROPHAGES POLARIZED WITH IL-10',
  'RNA FROM MONOCYTE-DERIVED MACROPHAGES 12 HOURS AFTER CULTURED WITHOUT VIRUS',
  'U937-DERIVED MACROPHAGES',
  'IPSC DERIVED MACROPHAGES',
  'IPSC-DERIVED MACROPHAGE',
  'MACROPHAGES_ACP_24 HOURS',
  'MACROPHAGE CELL LINE',
  'H1 ESC-DERIVED M2 MACROPHAGES',
  'CONTROL MACROPHAGE',
  'BAL MACROPHAGES',
  'PERIPHERAL_BLOOD_MACROPHAGE-M2_SICTRL',
  'DONOR1 -MACROPHAGE',
  'PERIPHERAL_BLOOD_MACROPHAGE-M1_SICTRL',
  'MACROPHAGES CADM1 POS',
  'IPSC-MACROPHAGE BY SPINNER SYSTEM',
  'PLEURAL  MACROPHAGES',
  'MONOCYTE DERIVED MACROPHAGES (MDM)',
  'MESECHEMAL STEM CELL, HUMAN UMBILICAL VEIN ENDOTHELIAL CELLS, MACROPHAGES',
  'MONOCYTES DERIVED MACROPHAGES',
  'MACROPHAGE 2 CONTROL REPLICATE 1',
  'PERIPHERAL BLOOD-DERIVED MACROPHAGES',
  'HESC-DERIVED MACROPHAGES',
  'MACROPHAGES POLARIZED WITH IL-4 AND IL-13',
  'M2 MACROPHAGES',
  'MACROPHAGE_BG_24HR_5D_MEDIA',
  'HUMAN MONOCYTE DERIVED MACROPHAGES',
  'PRIMARY HUMAN MONOCYTE-DERIVED MACROPHAGES, IFN-Î³',
  'MACROPHAGE VEGFR3',
  'HUMAN MACROPHAGES',
  'MACROPHAGE_BG_24HR_5D_MEDIA_MTB_4H',
  'MONOCYTE-DERIVED M2 MACROPHAGES OBTAINED FROM PROMOCELL COMPANY  (C-12915)',
  'BLOOD-DERIVED MACROPHAGES_CONTROL',
  'HUMAN MACROPHAGE',
  'MONOCYTES-DERIVED MACROPHAGES (MDMS)',
  'MACROPHAGE REP1',
  'PERIPHERAL BLOOD MONOCYTE-DERIVED MACROPHAGES IL-4 POLARIZED',
  'PRIMARY MACROPHAGES',
  'SORTED AFLO CD206+ CD45+ MACROPHAGES FROM BALF',
  'PRIMARY CD14+-DERIVED MACROPHAGES',
  'HUMAN MONOCYTE-DERIVED MACROPHAGES (HMDMS)',
  'MACROPHAGE IN NORMOXIA 48H_REP#2',
  'HUMAN MONOCYTE-DERIVED MACROPHAGES',
  'MONOCYTE-DERIVED GM-CSF MACROPHAGES',
  'MONOCYTE-DERIVED MACROPHAGES',
  'IPSC-DERIVED M1 MACROPHAGE',
  'MACROPHAGE REP2',
  'MONOCYTE-DERIVED M1 MACROPHAGES OBTAINED FROM PROMOCELL COMPANY  (C-12914)',
  'PRIMARY MONOCYTE-DERIVED MACROPHAGES',
  'GM-CSF DERIVED MACROPHAGES',
  'MACROPHAGE_IGG',
  'MACROPHAGE REP3',
  'MACROPHAGE, DMSO',
  'MACROPHAGE IN NORMOXIA 24H_REP#2',
  'PRIMARY MONOCYTE DERIVED MACROPHAGES (MDM)',
  'HU-IPSC-MACROPHAGE, WAS-B',
  'COLONIC MACROPHAGES',
  'MACROPHAGE',
  'MACROPHAGE_6D_MEDIA',
  'PRIMARY HUMAN MACROPHAGES',
  'BLOOD MONOCYTE DERIVED M2 MACROPHAGE',
  'HUMAN PRIMARY MACROPHAGES',
  'IPSC-DERIVED M2 MACROPHAGE',
  'MACROPHAGES(BC8)',
  'IPSC-MACROPHAGE BY ADHERENCE SYSTEM',
  'CD14+ SELECTED MONOCYTES DIFFERENTIATED MACROPHAGES',
  'HUMAN DECIDUAL MACROPHAGE',
  'MONOCYTE DERIVED MACROPHAGES',
  'DIFFERENTIATING MACROPHAGE',
  'MONOCYTE-MACROPHAGE LINEAGE CELLS',
  'PBMC DERIVED MACROPHAGES',
  'RNA FROM MONOCYTE-DERIVED MACROPHAGES 36 HOURS AFTER CULTURED WITHOUT VIRUS',
  'HUMAN STEM CELL-DERIVED MACROPHAGE',
  'BLOOD-DERIVED MACROPHAGES_IL4',
  'MONOCYTE-DERIVED MACROPHAGES (MDMS)',
  'NON-POLARIZED MACROPHAGES',
  'GLIMEPIRIDE_MACROPHAGE',
  'MACROPHAGE 2 CONTROL REPLICATE 5',
  'HU-IPSC-MACROPHAGE-RNA, WAS-B',
  'SORTED AIRWAY MACROPHAGES',
  'HUMAN DIFFERENTIATED MACROPHAGE CELL',
  'ACTIVATED MACROPHAGE',
  'PSC MONOCYTE-DERIVED MACROPHAGES',
  'MACROPHAGE 1 CONTROL REPLICATE 1',
  'IN VITRO DERIVED M2 MACROPHAGES',
  'MONOCYTE DERIVED MACROPHAGES (MDMS)',
  'IPS-MACROPHAGE',
  'H1 ESC-DERIVED M0 MACROPHAGES',
  'MCSF MONOCYTE DERIVED MACROPHAGES',
  'PERIPHERAL BLOOD MONOCYTE DERIVED MACROPHAGES',
  'HUMAN MONOCYTE DERIVED MACROPHAGE',
  'ASCITES FLUID MACROPHAGE',
  'MACROPHAGES (MDMS)',
  'MACROPHAGE 2 CONTROL REPLICATE 3',
  'BLOOD DERIVED MACROPHAGES',
  'IPSC-DERIVED MACROPHAGES'],
 'Microglia': ['MICROGLIA FROM INDIV4',
  'MICROGLIA_PU',
  'HUMAN_E3/E4_HEALTHY_IMICROGLIA',
  'MICROGLIA CELL LINE',
  'H1 ESC-DERIVED MICROGLIA',
  'IN VITRO DIFFERENTIATED MICROGLIA 60D',
  'IPSC5-DERIVED MICROGLIA',
  'IPSC-DERIVED MICROGLIA',
  'HUMAN PRIMARY MICROGLIA',
  'IPSC DERIVED HUMAN MICROGLIA',
  'HUMAN STEM CELL-DERIVED MICROGLIA',
  'RETINAL MICROGLIA',
  'HIPSC-DERIVED MICROGLIA',
  'EX VIVO ADULT MICROGLIA',
  'IPS-DERIVED MICROGLIA',
  'HUMAN IPS MICROGLIA',
  'HUMAN PRIMARY MICROGLIA SERUM FREE',
  'MICROGLIA',
  'PSEN1Î\x94E9_IPSC-MICROGLIA',
  'MICROGLIA FROM INDIV1',
  'IPSC-DERIVED MICROGLIA CELLS',
  'FETAL MICROGLIA',
  'HUMAN RETINAL MICROGLIA',
  'IPSC7-DERIVED MICROGLIA',
  'IN VITRO DIFFERENTIATED MICROGLIA 10D',
  'FETAL MICROGLIA (CLONEXPRESS, #HMG030)',
  'MICROGLIA FROM INDIV2',
  'PRIMARY  FETAL MICROGLIA',
  'IPSC1-DERIVED MICROGLIA',
  'OMG MICROGLIA',
  'WTC11 IPSC-DERIVED MICROGLIA',
  'CD11 HIPSC-DERIVED MICROGLIA',
  'MICROGLIA FROM CORPUS CALLOSUM',
  'HIPSC-DERIVED MICROGLIA (MG01)',
  'IPSC DERIVED MICROGLIA',
  'IPSC2-DERIVED MICROGLIA',
  'IPSC4-DERIVED MICROGLIA',
  'MICROGLIA FROM OCCIPITAL CORTEX',
  'HIPSC-MICROGLIA',
  'HUMAN_E4/E4_HEALTHY_IMICROGLIA',
  'IPS MICROGLIA',
  'DIFFERENTIATED MICROGLIA FROM THE PGP1 IPS CELL LINE (SYNTHEGO)',
  'IPSC3-DERIVED MICROGLIA',
  'MICROGLIA_CK',
  'IPSC-MICROGLIA',
  'MICROGLIA FROM INDIV3',
  'ADULT MICROGLIA',
  'HUMAN_E3/E3_HEALTHY_IMICROGLIA',
  'CD21 HIPSC-DERIVED MICROGLIA',
  'IPSC6-DERIVED MICROGLIA'],
 'Monocyte': ['GROUP 2_MONOCYTE',
  'CONTROL MONOCYTE SAMPLE FROM PERIPHERAL BLOOD OF HEALTHY VOLUNTEER',
  'PSC MONOCYTES',
  'MONOCYTE DONOR 1',
  'HUMAN CLASSICAL MONOCYTES',
  'PERIPHERAL BLOOD MONOCYTES (CD14+)',
  'CD14+ HEALTHY MONOCYTE',
  'IN VITRO DIFFERENTIATED MONOCYTES (FROM CORD BLOOD CD34+ CELLS)',
  'CD14-POSITIVE MONOCYTES',
  'MONOCYTE/CD14+16-',
  'AGE-MATCHED CONTROL CLASSICAL MONOCYTES',
  'ISOLATED HUMAN MONOCYTES, BEFORE CONSUMPTION OF A VEGETABLE FAT SHAKE',
  'PRIMARY MONOCYTE',
  'MONOCYTES, HEALTHY',
  'HUMAN PRIMARY MONOCYTES ISOLATED FROM PBMC OF HEALTHY DONORS',
  'CONTROL, CLASSICAL MONOCYTE',
  'DAY0_MONOCYTES_DONOR2',
  'CIRCULATING CD14+ MONOCYTES',
  'DAY0_MONOCYTES_DONOR4',
  'DAY0_MONOCYTES_DONOR1',
  'MONOCYTE CELL CULTURE',
  'MONOCYTES OBTAINED FROM LUNG TISSUE',
  'HUMAN CD14+ MONOCYTES',
  'PRIMARY MONOCYTESCD14+(BC13)',
  'CONTROL_MONOCYTES',
  'GROUP 1_MONOCYTE',
  'DONOR 1 ISOLATED MONOCYTES',
  'HUMAN PERIPHERAL BLOOD CD14+ MONOCYTE_NEGATIVE CONTROL',
  'HOMO SAPIENS CD14-POSITIVE MONOCYTE PRIMARY CELL',
  'SORTED MONOCYTES',
  'CD14POSCD16POS MONOCYTE',
  'ISOLATED HUMAN MONOCYTES, 6H AFTER CONSUMPTION OF A VEGETABLE FAT SHAKE',
  'ISOLATED HUMAN MONOCYTES, 6H AFTER CONSUMPTION OF A MILK FAT GLOBULE MEMBRANE SHAKE',
  'NOS_MONOCYTES',
  'PBMC MONOCYTES',
  'CLASSICAL MONOCYTES FROM PERIPHERAL BLOOD',
  'CD14POSCD16NEG MONOCYTE',
  'MONOCYTE/CD14+16+',
  'PURIFIED HUMAN MONOCYTES',
  'DAY0_MONOCYTES_DONOR3',
  'PRIMARY MONOCYTES(REST CELL POPULATION AFTER CD14+ SELECTION)(BC13)',
  'MONOCYTE CELL LINE',
  'INACTIVE_MONOCYTES',
  'DONOR 2 ISOLATED MONOCYTES',
  'PRIMARY MONOCYTES_INTACT LAP',
  'PRIMARY MONOCYTES(REST CELL POPULATION AFTER CD14+ SELECTION)(BC14)',
  'CD14+_MONOCYTES',
  'PRIMARY MONOCYTES(BC12)',
  'PB MONOCYTE SIBLING',
  'MONOCYTES FROM HEALTHY HUMAN DONNOR',
  'BLOOD CLASSICAL MONOCYTE',
  'DAY0_MONOCYTES_DONOR5',
  'MONOCYTES FROM PBMC',
  'MONOCYTE',
  'CD14+ MONOCYTES',
  'HUMAN PERIPHERAL BLOOD CD14+ MONOCYTE_MIR-155 MIMIC',
  'MPN MONOCYTE',
  'CD14+ BLOOD MONOCYTE',
  'HUMAN MONOCYTE',
  'DONOR 3 ISOLATED MONOCYTES',
  'PRIMARY MONOCYTES',
  'CIRCULATING BLOOD BULK MONOCYTES',
  'PRIMARY HUMAN CD14+/CD16+ MONOCYTES',
  'MONOCYTES FROM HEALTHY DONOR',
  'ISOLATED HUMAN MONOCYTES, BEFORE CONSUMPTION OF A ANHYDROUS MILK FAT SHAKE',
  'ISOLATED HUMAN MONOCYTES, 6H AFTER CONSUMPTION OF A ANHYDROUS MILK FAT SHAKE',
  'PRIMARY MONOCYTES(BC9)',
  'MONOCYTES',
  'MONOCYTES CCR2 POS',
  'PERIPHERAL BLOOD MONOCYTES FROM ADULT',
  'CLASSICAL MONOCYTES',
  'PERIPHERAL BLOOD MONOCYTES',
  'MONOCYTE DONOR 2',
  'HUMAN BLOOD MONOCYTES',
  'MONOCYTE CELLS',
  'PERIPHERAL BLOOD MONOCYTE',
  'CONTROL MONOCYTE CULTURED IN MEDIA (RPMI) FOR 24 HOURS',
  'IMONOCYTES',
  'HUMAN PRIMARY MONOCYTES ACTIVATED BY SURFACE-ADSORPTION',
  'CD14+ MPN MONOCYTE',
  'CD14+_MONOCYTE',
  'PERIPHERAL MONOCYTES',
  'BLOOD MONOCYTES',
  'HUMAN, MONOCYTE',
  'CD14+ MONOCYTE',
  'NOS/MAS_MONOCYTES',
  'HUMAN BLOOD PRIMARY MONOCYTES',
  'HOMO SAPIENS CD14-POSITIVE MONOCYTE PRIMARY CELL, PRESERVED BY CRYOPRESERVATION',
  'PRIMARY HUMAN MATURE MONOCYTES',
  'PURIFIED CD14+ MONOCYTES FROM HEALTHY HUMAN, IMMEDIATELY AFTER ISOLATION',
  'PRIMARY MONOCYTES(BC8)',
  'PERIPHEREAL BLOOD MONOCYTES',
  'MONOCYTES-CD14+',
  'MATURE MONOCYTES',
  'HUMAN PERIPHERAL BLOOD MONOCYTES',
  'HUMAN MONOCYTES',
  'HUMAN MONOCYTE ISOLATION FROM BUFFY COATS',
  'ACTIVE_MONOCYTES',
  'PRIMARY MONOCYTESCD14+(BC14)',
  'SORTED CD14+ MONOCYTES FROM BLOOD',
  'MONOCYTE DONOR 3',
  'HUMAN PRIMARY MONOCYTES (> 90% PURITIY)',
  'HUMAN INTERMEDIATE MONOCYTES',
  'HUMAN PRIMARY MONOCYTES',
  'PRIMARY MONOCYTES(BC11)',
  'INTERMEDIATE MONOCYTES',
  'MONOCYTE/CD14+',
  'HUMAN MONOCYTE CELL LINE',
  'MONOCYTES_NAIVE',
  'MONOCYTES ISOLATED FROM BLOOD',
  'ISOLATED HUMAN MONOCYTES, BEFORE CONSUMPTION OF A MILK FAT GLOBULE MEMBRANE SHAKE',
  'GROUP 3_MONOCYTE',
  'CULTURED MONOCYTES FROM PERIPHERAL BLOOD OF HEALTHY DONOR',
  'UMBILICAL CORD BLOOD PURIFIED CD14+ MONOCYTES'],
 'other': ['OSTEOCLAST DAY 10 IN VITRO DONOR 3',
  'OSTEOCLAST DAY 10 IN VITRO DONOR 4',
  'OSTEOCLAST DAY 10 IN VITRO DONOR 5',
  'OSTEOCLAST DAY 10 IN VITRO DONOR 2',
  'OSTEOCLAST DAY 10 IN VITRO DONOR 1',
  'OSTEOCLAST DAY 10 IN VITRO DONOR 8',
  'OSTEOCLAST DAY 10 IN VITRO DONOR 7',
  'CD14+ MONOCYTES DERIVED OSTEOCLASTS IN VITRO',
  'OSTEOCLAST DAY 10 IN VITRO DONOR 6',
  'HUMAN HEPATIC MACROPHAGES',
  'SORTED KUPFFER CELLS',
  'LIVER (HEPATOCYTES + KUPFFER CELLS)',
  'HUMAN KUPFFER CELLS',
  'LANGERHANS CELL-DERIVED DENDRITIC CELL',
  'PANCREATIC ISLETS OF LANGERHANS_BLEO',
  'PANCREATIC ISLETS OF LANGERHANS_VEH',
  'MONOCYTE-DERIVED LANGERHANS CELLS',
  'MONOCYTE-DERIVED LANGERHANS CELL',
  'ISLETS OF LANGERHANS',
  'DGM-00342_D1, ALVEOLAR MACROPHAGE',
  'DGM-00244_D7, ALVEOLAR MACROPHAGE',
  'DGM-00342_D7, ALVEOLAR MACROPHAGE',
  'DGM-11213_D7, ALVEOLAR MACROPHAGE',
  'ALVEOLAR MACROPHAGE DONOR 7',
  'DGM-13029_D7, ALVEOLAR MACROPHAGE',
  'DGM-00244_D1, ALVEOLAR MACROPHAGE',
  'DGM-01774_D7, ALVEOLAR MACROPHAGE',
  'DGM-01774_D1, ALVEOLAR MACROPHAGE',
  'ALVEOLAR MACROPHAGES, POST-ALLERGEN CHALLENGE',
  'ALVEOLAR MACROPHAGES, PRE-ALLERGEN CHALLENGE',
  'DGM-12941_D1, ALVEOLAR MACROPHAGE',
  'MACROPHAGES ISOLATED FROM THE MACROPHAGE-CONTAINED ALVEOLAR ORGANOID- 2 WEEKS POST COCULTURE',
  'DGM-13039_D7, ALVEOLAR MACROPHAGE',
  'DGM-13029_D1, ALVEOLAR MACROPHAGE',
  'DGM-12942_D1, ALVEOLAR MACROPHAGE',
  'ALVEOLAR MACROPHAGE',
  'DGM-13050_D1, ALVEOLAR MACROPHAGE',
  'DGM-12971_D1, ALVEOLAR MACROPHAGE',
  'ALVEOLAR MACROPHAGES OBTAINED FROM LUNG TISSUE',
  'DGM-12971_D7, ALVEOLAR MACROPHAGE',
  'DGM-12942_D7, ALVEOLAR MACROPHAGE',
  'ALVEOLAR MACROPHAGE DONOR 4',
  'BRONCHOALVEOLARÂ\xa0LAVAGE,Â\xa0ALVEOLARÂ\xa0MACROPHAGE',
  'DGM-13050_D7, ALVEOLAR MACROPHAGE',
  'ALVEOLAR MACROPHAGES',
  'DGM-11213_D1, ALVEOLAR MACROPHAGE',
  'DGM-13039_D1, ALVEOLAR MACROPHAGE',
  'DGM-12941_D7, ALVEOLAR MACROPHAGE']}

### Filters human_tpm_v2.2_NOSC.h5 into a filtered file containing source names in class_sample_dict

In [6]:
transcript_file_path = "/scratch/by2372/pipeline/ARCHS4_Macrophages/human_tpm_v2.2_NOSC.h5"
a4.ls(transcript_file_path)

data
│ expression            float32 | (271742, 661840)
meta
│ samples
│   characteristics_ch1   str    | (661840,)
│   source_name_ch1       str    | (661840,)
│ transcripts
│   ensembl_id            str    | (271742,)
│   symbol                str    | (271742,)

In [7]:

with h5py.File(transcript_file_path, "r") as fin, h5py.File('filtered_ARCHS4_4_class.h5', 'w') as fout:

    # copy the ensembl_ids and gene symbols to the new h5 file
    fin.copy("meta/transcripts/ensembl_id", fout)
    fin.copy("meta/transcripts/symbol", fout) 
    
    # Navigate to the metadata group for source names
    source_name_ds = fin['meta/samples/source_name_ch1']

    # Read all names and decode bytes to strings
    source_names = source_name_ds[:]
    if isinstance(source_names[0], bytes):
        source_names = [s.decode('utf-8') for s in source_names]

    # Get dataset info
    expr_dataset = fin['data/expression']
    n_genes, n_samples = expr_dataset.shape

    filtered_dataset = fout.create_dataset(
        "data/filtered_expression",
        (n_genes, 0),                    # start with 0 samples
        maxshape=(n_genes, None),        # allow dynamic extension
        dtype=expr_dataset.dtype,
        chunks=True
    )
    
    class_name_dataset = fout.create_dataset(
        "class_name",
        (0,),                            # start empty
        maxshape=(None,),                # allow appending
        dtype=source_name_ds.dtype,
        chunks=True
    )

    current_pos = 0

    for key, value in class_sample_dict.items():

        print("Matching indices for " + str(key))

        
        matched_indices = []
        class_names = []
        
        for filt_name in set(value): 
            matched_indices.extend([
                i for i, n in enumerate(source_names)
                if n.lower() == filt_name.lower()
            ])

        matched_indices.sort()
        n_new = len(matched_indices)
        print(str(n_new))
        cur_class_names = [key] * n_new
        class_names.append(cur_class_names)

        filtered_dataset.resize((n_genes, current_pos + n_new))
        class_name_dataset.resize((current_pos + n_new,))
        
        # Process in chunks of genes instead of loading all at once
        chunk_size = 1000  # Adjust based on your memory
        iteration = 0
        for start_gene in range(0, n_genes, chunk_size):
            end_gene = min(start_gene + chunk_size, n_genes)
            
            # Read chunk of data for matched samples only
            chunk_data = expr_dataset[start_gene:end_gene, matched_indices]
            
            # Write to output
            filtered_dataset[start_gene:end_gene, current_pos:current_pos + n_new] = chunk_data
            iteration = iteration + 1
            print("Iteration " + str(iteration)+ " is done.")
            sys.stdout.flush()


        class_name_dataset[current_pos:current_pos + n_new] = class_names
        
        current_pos += n_new

Matching indices for Macrophage
4183
Iteration 1 is done.
Iteration 2 is done.
Iteration 3 is done.
Iteration 4 is done.
Iteration 5 is done.
Iteration 6 is done.
Iteration 7 is done.
Iteration 8 is done.
Iteration 9 is done.
Iteration 10 is done.
Iteration 11 is done.
Iteration 12 is done.
Iteration 13 is done.
Iteration 14 is done.
Iteration 15 is done.
Iteration 16 is done.
Iteration 17 is done.
Iteration 18 is done.
Iteration 19 is done.
Iteration 20 is done.
Iteration 21 is done.
Iteration 22 is done.
Iteration 23 is done.
Iteration 24 is done.
Iteration 25 is done.
Iteration 26 is done.
Iteration 27 is done.
Iteration 28 is done.
Iteration 29 is done.
Iteration 30 is done.
Iteration 31 is done.
Iteration 32 is done.
Iteration 33 is done.
Iteration 34 is done.
Iteration 35 is done.
Iteration 36 is done.
Iteration 37 is done.
Iteration 38 is done.
Iteration 39 is done.
Iteration 40 is done.
Iteration 41 is done.
Iteration 42 is done.
Iteration 43 is done.
Iteration 44 is done.
Iteration 45 is done.
Iteration 46 is done.
Iteration 47 is done.
Iteration 48 is done.
Iteration 49 is done.
Iteration 50 is done.
Iteration 51 is done.
Iteration 52 is done.
Iteration 53 is done.
Iteration 54 is done.
Iteration 55 is done.
Iteration 56 is done.
Iteration 57 is done.
Iteration 58 is done.
Iteration 59 is done.
Iteration 60 is done.
Iteration 61 is done.
Iteration 62 is done.
Iteration 63 is done.
Iteration 64 is done.
Iteration 65 is done.
Iteration 66 is done.
Iteration 67 is done.
Iteration 68 is done.
Iteration 69 is done.
Iteration 70 is done.
Iteration 71 is done.
Iteration 72 is done.
Iteration 73 is done.
Iteration 74 is done.
Iteration 75 is done.
Iteration 76 is done.
Iteration 77 is done.
Iteration 78 is done.
Iteration 79 is done.
Iteration 80 is done.
Iteration 81 is done.
Iteration 82 is done.
Iteration 83 is done.
Iteration 84 is done.
Iteration 85 is done.
Iteration 86 is done.
Iteration 87 is done.
Iteration 88 is done.
Iteration 89 is done.
Iteration 90 is done.
Iteration 91 is done.
Iteration 92 is done.
Iteration 93 is done.
Iteration 94 is done.
Iteration 95 is done.
Iteration 96 is done.
Iteration 97 is done.
Iteration 98 is done.
Iteration 99 is done.
Iteration 100 is done.
Iteration 101 is done.
Iteration 102 is done.
Iteration 103 is done.
Iteration 104 is done.
Iteration 105 is done.
Iteration 106 is done.
Iteration 107 is done.
Iteration 108 is done.
Iteration 109 is done.
Iteration 110 is done.
Iteration 111 is done.
Iteration 112 is done.
Iteration 113 is done.
Iteration 114 is done.
Iteration 115 is done.
Iteration 116 is done.
Iteration 117 is done.
Iteration 118 is done.
Iteration 119 is done.
Iteration 120 is done.
Iteration 121 is done.
Iteration 122 is done.
Iteration 123 is done.
Iteration 124 is done.
Iteration 125 is done.
Iteration 126 is done.
Iteration 127 is done.
Iteration 128 is done.
Iteration 129 is done.
Iteration 130 is done.
Iteration 131 is done.
Iteration 132 is done.
Iteration 133 is done.
Iteration 134 is done.
Iteration 135 is done.
Iteration 136 is done.
Iteration 137 is done.
Iteration 138 is done.
Iteration 139 is done.
Iteration 140 is done.
Iteration 141 is done.
Iteration 142 is done.
Iteration 143 is done.
Iteration 144 is done.
Iteration 145 is done.
Iteration 146 is done.
Iteration 147 is done.
Iteration 148 is done.
Iteration 149 is done.
Iteration 150 is done.
Iteration 151 is done.
Iteration 152 is done.
Iteration 153 is done.
Iteration 154 is done.
Iteration 155 is done.
Iteration 156 is done.
Iteration 157 is done.
Iteration 158 is done.
Iteration 159 is done.
Iteration 160 is done.
Iteration 161 is done.
Iteration 162 is done.
Iteration 163 is done.
Iteration 164 is done.
Iteration 165 is done.
Iteration 166 is done.
Iteration 167 is done.
Iteration 168 is done.
Iteration 169 is done.
Iteration 170 is done.
Iteration 171 is done.
Iteration 172 is done.
Iteration 173 is done.
Iteration 174 is done.
Iteration 175 is done.
Iteration 176 is done.
Iteration 177 is done.
Iteration 178 is done.
Iteration 179 is done.
Iteration 180 is done.
Iteration 181 is done.
Iteration 182 is done.
Iteration 183 is done.
Iteration 184 is done.
Iteration 185 is done.
Iteration 186 is done.
Iteration 187 is done.
Iteration 188 is done.
Iteration 189 is done.
Iteration 190 is done.
Iteration 191 is done.
Iteration 192 is done.
Iteration 193 is done.
Iteration 194 is done.
Iteration 195 is done.
Iteration 196 is done.
Iteration 197 is done.
Iteration 198 is done.
Iteration 199 is done.
Iteration 200 is done.
Iteration 201 is done.
Iteration 202 is done.
Iteration 203 is done.
Iteration 204 is done.
Iteration 205 is done.
Iteration 206 is done.
Iteration 207 is done.
Iteration 208 is done.
Iteration 209 is done.
Iteration 210 is done.
Iteration 211 is done.
Iteration 212 is done.
Iteration 213 is done.
Iteration 214 is done.
Iteration 215 is done.
Iteration 216 is done.
Iteration 217 is done.
Iteration 218 is done.
Iteration 219 is done.
Iteration 220 is done.
Iteration 221 is done.
Iteration 222 is done.
Iteration 223 is done.
Iteration 224 is done.
Iteration 225 is done.
Iteration 226 is done.
Iteration 227 is done.
Iteration 228 is done.
Iteration 229 is done.
Iteration 230 is done.
Iteration 231 is done.
Iteration 232 is done.
Iteration 233 is done.
Iteration 234 is done.
Iteration 235 is done.
Iteration 236 is done.
Iteration 237 is done.
Iteration 238 is done.
Iteration 239 is done.
Iteration 240 is done.
Iteration 241 is done.
Iteration 242 is done.
Iteration 243 is done.
Iteration 244 is done.
Iteration 245 is done.
Iteration 246 is done.
Iteration 247 is done.
Iteration 248 is done.
Iteration 249 is done.
Iteration 250 is done.
Iteration 251 is done.
Iteration 252 is done.
Iteration 253 is done.
Iteration 254 is done.
Iteration 255 is done.
Iteration 256 is done.
Iteration 257 is done.
Iteration 258 is done.
Iteration 259 is done.
Iteration 260 is done.
Iteration 261 is done.
Iteration 262 is done.
Iteration 263 is done.
Iteration 264 is done.
Iteration 265 is done.
Iteration 266 is done.
Iteration 267 is done.
Iteration 268 is done.
Iteration 269 is done.
Iteration 270 is done.
Iteration 271 is done.
Iteration 272 is done.
Matching indices for Microglia
672
Iteration 1 is done.
Iteration 2 is done.
Iteration 3 is done.
Iteration 4 is done.
Iteration 5 is done.
Iteration 6 is done.
Iteration 7 is done.
Iteration 8 is done.
Iteration 9 is done.
Iteration 10 is done.
Iteration 11 is done.
Iteration 12 is done.
Iteration 13 is done.
Iteration 14 is done.
Iteration 15 is done.
Iteration 16 is done.
Iteration 17 is done.
Iteration 18 is done.
Iteration 19 is done.
Iteration 20 is done.
Iteration 21 is done.
Iteration 22 is done.
Iteration 23 is done.
Iteration 24 is done.
Iteration 25 is done.
Iteration 26 is done.
Iteration 27 is done.
Iteration 28 is done.
Iteration 29 is done.
Iteration 30 is done.
Iteration 31 is done.
Iteration 32 is done.
Iteration 33 is done.
Iteration 34 is done.
Iteration 35 is done.
Iteration 36 is done.
Iteration 37 is done.
Iteration 38 is done.
Iteration 39 is done.
Iteration 40 is done.
Iteration 41 is done.
Iteration 42 is done.
Iteration 43 is done.
Iteration 44 is done.
Iteration 45 is done.
Iteration 46 is done.
Iteration 47 is done.
Iteration 48 is done.
Iteration 49 is done.
Iteration 50 is done.
Iteration 51 is done.
Iteration 52 is done.
Iteration 53 is done.
Iteration 54 is done.
Iteration 55 is done.
Iteration 56 is done.
Iteration 57 is done.
Iteration 58 is done.
Iteration 59 is done.
Iteration 60 is done.
Iteration 61 is done.
Iteration 62 is done.
Iteration 63 is done.
Iteration 64 is done.
Iteration 65 is done.
Iteration 66 is done.
Iteration 67 is done.
Iteration 68 is done.
Iteration 69 is done.
Iteration 70 is done.
Iteration 71 is done.
Iteration 72 is done.
Iteration 73 is done.
Iteration 74 is done.
Iteration 75 is done.
Iteration 76 is done.
Iteration 77 is done.
Iteration 78 is done.
Iteration 79 is done.
Iteration 80 is done.
Iteration 81 is done.
Iteration 82 is done.
Iteration 83 is done.
Iteration 84 is done.
Iteration 85 is done.
Iteration 86 is done.
Iteration 87 is done.
Iteration 88 is done.
Iteration 89 is done.
Iteration 90 is done.
Iteration 91 is done.
Iteration 92 is done.
Iteration 93 is done.
Iteration 94 is done.
Iteration 95 is done.
Iteration 96 is done.
Iteration 97 is done.
Iteration 98 is done.
Iteration 99 is done.
Iteration 100 is done.
Iteration 101 is done.
Iteration 102 is done.
Iteration 103 is done.
Iteration 104 is done.
Iteration 105 is done.
Iteration 106 is done.
Iteration 107 is done.
Iteration 108 is done.
Iteration 109 is done.
Iteration 110 is done.
Iteration 111 is done.
Iteration 112 is done.
Iteration 113 is done.
Iteration 114 is done.
Iteration 115 is done.
Iteration 116 is done.
Iteration 117 is done.
Iteration 118 is done.
Iteration 119 is done.
Iteration 120 is done.
Iteration 121 is done.
Iteration 122 is done.
Iteration 123 is done.
Iteration 124 is done.
Iteration 125 is done.
Iteration 126 is done.
Iteration 127 is done.
Iteration 128 is done.
Iteration 129 is done.
Iteration 130 is done.
Iteration 131 is done.
Iteration 132 is done.
Iteration 133 is done.
Iteration 134 is done.
Iteration 135 is done.
Iteration 136 is done.
Iteration 137 is done.
Iteration 138 is done.
Iteration 139 is done.
Iteration 140 is done.
Iteration 141 is done.
Iteration 142 is done.
Iteration 143 is done.
Iteration 144 is done.
Iteration 145 is done.
Iteration 146 is done.
Iteration 147 is done.
Iteration 148 is done.
Iteration 149 is done.
Iteration 150 is done.
Iteration 151 is done.
Iteration 152 is done.
Iteration 153 is done.
Iteration 154 is done.
Iteration 155 is done.
Iteration 156 is done.
Iteration 157 is done.
Iteration 158 is done.
Iteration 159 is done.
Iteration 160 is done.
Iteration 161 is done.
Iteration 162 is done.
Iteration 163 is done.
Iteration 164 is done.
Iteration 165 is done.
Iteration 166 is done.
Iteration 167 is done.
Iteration 168 is done.
Iteration 169 is done.
Iteration 170 is done.
Iteration 171 is done.
Iteration 172 is done.
Iteration 173 is done.
Iteration 174 is done.
Iteration 175 is done.
Iteration 176 is done.
Iteration 177 is done.
Iteration 178 is done.
Iteration 179 is done.
Iteration 180 is done.
Iteration 181 is done.
Iteration 182 is done.
Iteration 183 is done.
Iteration 184 is done.
Iteration 185 is done.
Iteration 186 is done.
Iteration 187 is done.
Iteration 188 is done.
Iteration 189 is done.
Iteration 190 is done.
Iteration 191 is done.
Iteration 192 is done.
Iteration 193 is done.
Iteration 194 is done.
Iteration 195 is done.
Iteration 196 is done.
Iteration 197 is done.
Iteration 198 is done.
Iteration 199 is done.
Iteration 200 is done.
Iteration 201 is done.
Iteration 202 is done.
Iteration 203 is done.
Iteration 204 is done.
Iteration 205 is done.
Iteration 206 is done.
Iteration 207 is done.
Iteration 208 is done.
Iteration 209 is done.
Iteration 210 is done.
Iteration 211 is done.
Iteration 212 is done.
Iteration 213 is done.
Iteration 214 is done.
Iteration 215 is done.
Iteration 216 is done.
Iteration 217 is done.
Iteration 218 is done.
Iteration 219 is done.
Iteration 220 is done.
Iteration 221 is done.
Iteration 222 is done.
Iteration 223 is done.
Iteration 224 is done.
Iteration 225 is done.
Iteration 226 is done.
Iteration 227 is done.
Iteration 228 is done.
Iteration 229 is done.
Iteration 230 is done.
Iteration 231 is done.
Iteration 232 is done.
Iteration 233 is done.
Iteration 234 is done.
Iteration 235 is done.
Iteration 236 is done.
Iteration 237 is done.
Iteration 238 is done.
Iteration 239 is done.
Iteration 240 is done.
Iteration 241 is done.
Iteration 242 is done.
Iteration 243 is done.
Iteration 244 is done.
Iteration 245 is done.
Iteration 246 is done.
Iteration 247 is done.
Iteration 248 is done.
Iteration 249 is done.
Iteration 250 is done.
Iteration 251 is done.
Iteration 252 is done.
Iteration 253 is done.
Iteration 254 is done.
Iteration 255 is done.
Iteration 256 is done.
Iteration 257 is done.
Iteration 258 is done.
Iteration 259 is done.
Iteration 260 is done.
Iteration 261 is done.
Iteration 262 is done.
Iteration 263 is done.
Iteration 264 is done.
Iteration 265 is done.
Iteration 266 is done.
Iteration 267 is done.
Iteration 268 is done.
Iteration 269 is done.
Iteration 270 is done.
Iteration 271 is done.
Iteration 272 is done.
Matching indices for Monocyte
5497
Iteration 1 is done.
Iteration 2 is done.
Iteration 3 is done.
Iteration 4 is done.
Iteration 5 is done.
Iteration 6 is done.
Iteration 7 is done.
Iteration 8 is done.
Iteration 9 is done.
Iteration 10 is done.
Iteration 11 is done.
Iteration 12 is done.
Iteration 13 is done.
Iteration 14 is done.
Iteration 15 is done.
Iteration 16 is done.
Iteration 17 is done.
Iteration 18 is done.
Iteration 19 is done.
Iteration 20 is done.
Iteration 21 is done.
Iteration 22 is done.
Iteration 23 is done.
Iteration 24 is done.
Iteration 25 is done.
Iteration 26 is done.
Iteration 27 is done.
Iteration 28 is done.
Iteration 29 is done.
Iteration 30 is done.
Iteration 31 is done.
Iteration 32 is done.
Iteration 33 is done.
Iteration 34 is done.
Iteration 35 is done.
Iteration 36 is done.
Iteration 37 is done.
Iteration 38 is done.
Iteration 39 is done.
Iteration 40 is done.
Iteration 41 is done.
Iteration 42 is done.
Iteration 43 is done.
Iteration 44 is done.
Iteration 45 is done.
Iteration 46 is done.
Iteration 47 is done.
Iteration 48 is done.
Iteration 49 is done.
Iteration 50 is done.
Iteration 51 is done.
Iteration 52 is done.
Iteration 53 is done.
Iteration 54 is done.
Iteration 55 is done.
Iteration 56 is done.
Iteration 57 is done.
Iteration 58 is done.
Iteration 59 is done.
Iteration 60 is done.
Iteration 61 is done.
Iteration 62 is done.
Iteration 63 is done.
Iteration 64 is done.
Iteration 65 is done.
Iteration 66 is done.
Iteration 67 is done.
Iteration 68 is done.
Iteration 69 is done.
Iteration 70 is done.
Iteration 71 is done.
Iteration 72 is done.
Iteration 73 is done.
Iteration 74 is done.
Iteration 75 is done.
Iteration 76 is done.
Iteration 77 is done.
Iteration 78 is done.
Iteration 79 is done.
Iteration 80 is done.
Iteration 81 is done.
Iteration 82 is done.
Iteration 83 is done.
Iteration 84 is done.
Iteration 85 is done.
Iteration 86 is done.
Iteration 87 is done.
Iteration 88 is done.
Iteration 89 is done.
Iteration 90 is done.
Iteration 91 is done.
Iteration 92 is done.
Iteration 93 is done.
Iteration 94 is done.
Iteration 95 is done.
Iteration 96 is done.
Iteration 97 is done.
Iteration 98 is done.
Iteration 99 is done.
Iteration 100 is done.
Iteration 101 is done.
Iteration 102 is done.
Iteration 103 is done.
Iteration 104 is done.
Iteration 105 is done.
Iteration 106 is done.
Iteration 107 is done.
Iteration 108 is done.
Iteration 109 is done.
Iteration 110 is done.
Iteration 111 is done.
Iteration 112 is done.
Iteration 113 is done.
Iteration 114 is done.
Iteration 115 is done.
Iteration 116 is done.
Iteration 117 is done.
Iteration 118 is done.
Iteration 119 is done.
Iteration 120 is done.
Iteration 121 is done.
Iteration 122 is done.
Iteration 123 is done.
Iteration 124 is done.
Iteration 125 is done.
Iteration 126 is done.
Iteration 127 is done.
Iteration 128 is done.
Iteration 129 is done.
Iteration 130 is done.
Iteration 131 is done.
Iteration 132 is done.
Iteration 133 is done.
Iteration 134 is done.
Iteration 135 is done.
Iteration 136 is done.
Iteration 137 is done.
Iteration 138 is done.
Iteration 139 is done.
Iteration 140 is done.
Iteration 141 is done.
Iteration 142 is done.
Iteration 143 is done.
Iteration 144 is done.
Iteration 145 is done.
Iteration 146 is done.
Iteration 147 is done.
Iteration 148 is done.
Iteration 149 is done.
Iteration 150 is done.
Iteration 151 is done.
Iteration 152 is done.
Iteration 153 is done.
Iteration 154 is done.
Iteration 155 is done.
Iteration 156 is done.
Iteration 157 is done.
Iteration 158 is done.
Iteration 159 is done.
Iteration 160 is done.
Iteration 161 is done.
Iteration 162 is done.
Iteration 163 is done.
Iteration 164 is done.
Iteration 165 is done.
Iteration 166 is done.
Iteration 167 is done.
Iteration 168 is done.
Iteration 169 is done.
Iteration 170 is done.
Iteration 171 is done.
Iteration 172 is done.
Iteration 173 is done.
Iteration 174 is done.
Iteration 175 is done.
Iteration 176 is done.
Iteration 177 is done.
Iteration 178 is done.
Iteration 179 is done.
Iteration 180 is done.
Iteration 181 is done.
Iteration 182 is done.
Iteration 183 is done.
Iteration 184 is done.
Iteration 185 is done.
Iteration 186 is done.
Iteration 187 is done.
Iteration 188 is done.
Iteration 189 is done.
Iteration 190 is done.
Iteration 191 is done.
Iteration 192 is done.
Iteration 193 is done.
Iteration 194 is done.
Iteration 195 is done.
Iteration 196 is done.
Iteration 197 is done.
Iteration 198 is done.
Iteration 199 is done.
Iteration 200 is done.
Iteration 201 is done.
Iteration 202 is done.
Iteration 203 is done.
Iteration 204 is done.
Iteration 205 is done.
Iteration 206 is done.
Iteration 207 is done.
Iteration 208 is done.
Iteration 209 is done.
Iteration 210 is done.
Iteration 211 is done.
Iteration 212 is done.
Iteration 213 is done.
Iteration 214 is done.
Iteration 215 is done.
Iteration 216 is done.
Iteration 217 is done.
Iteration 218 is done.
Iteration 219 is done.
Iteration 220 is done.
Iteration 221 is done.
Iteration 222 is done.
Iteration 223 is done.
Iteration 224 is done.
Iteration 225 is done.
Iteration 226 is done.
Iteration 227 is done.
Iteration 228 is done.
Iteration 229 is done.
Iteration 230 is done.
Iteration 231 is done.
Iteration 232 is done.
Iteration 233 is done.
Iteration 234 is done.
Iteration 235 is done.
Iteration 236 is done.
Iteration 237 is done.
Iteration 238 is done.
Iteration 239 is done.
Iteration 240 is done.
Iteration 241 is done.
Iteration 242 is done.
Iteration 243 is done.
Iteration 244 is done.
Iteration 245 is done.
Iteration 246 is done.
Iteration 247 is done.
Iteration 248 is done.
Iteration 249 is done.
Iteration 250 is done.
Iteration 251 is done.
Iteration 252 is done.
Iteration 253 is done.
Iteration 254 is done.
Iteration 255 is done.
Iteration 256 is done.
Iteration 257 is done.
Iteration 258 is done.
Iteration 259 is done.
Iteration 260 is done.
Iteration 261 is done.
Iteration 262 is done.
Iteration 263 is done.
Iteration 264 is done.
Iteration 265 is done.
Iteration 266 is done.
Iteration 267 is done.
Iteration 268 is done.
Iteration 269 is done.
Iteration 270 is done.
Iteration 271 is done.
Iteration 272 is done.
Matching indices for other
423
Iteration 1 is done.
Iteration 2 is done.
Iteration 3 is done.
Iteration 4 is done.
Iteration 5 is done.
Iteration 6 is done.
Iteration 7 is done.
Iteration 8 is done.
Iteration 9 is done.
Iteration 10 is done.
Iteration 11 is done.
Iteration 12 is done.
Iteration 13 is done.
Iteration 14 is done.
Iteration 15 is done.
Iteration 16 is done.
Iteration 17 is done.
Iteration 18 is done.
Iteration 19 is done.
Iteration 20 is done.
Iteration 21 is done.
Iteration 22 is done.
Iteration 23 is done.
Iteration 24 is done.
Iteration 25 is done.
Iteration 26 is done.
Iteration 27 is done.
Iteration 28 is done.
Iteration 29 is done.
Iteration 30 is done.
Iteration 31 is done.
Iteration 32 is done.
Iteration 33 is done.
Iteration 34 is done.
Iteration 35 is done.
Iteration 36 is done.
Iteration 37 is done.
Iteration 38 is done.
Iteration 39 is done.
Iteration 40 is done.
Iteration 41 is done.
Iteration 42 is done.
Iteration 43 is done.
Iteration 44 is done.
Iteration 45 is done.
Iteration 46 is done.
Iteration 47 is done.
Iteration 48 is done.
Iteration 49 is done.
Iteration 50 is done.
Iteration 51 is done.
Iteration 52 is done.
Iteration 53 is done.
Iteration 54 is done.
Iteration 55 is done.
Iteration 56 is done.
Iteration 57 is done.
Iteration 58 is done.
Iteration 59 is done.
Iteration 60 is done.
Iteration 61 is done.
Iteration 62 is done.
Iteration 63 is done.
Iteration 64 is done.

# Following code will filter the database for TF genes only

In [8]:
filtered_file = "/scratch/by2372/pipeline/ARCHS4_Macrophages/Source_name_4_class/filtered_ARCHS4_4_class.h5"
tf_names = load_sample_names("/scratch/by2372/pipeline/tf_names.txt")
a4.ls(filtered_file)

class_name            str    | (10775,)
data
│ filtered_expression   float32 | (271742, 10775)
ensembl_id            str    | (271742,)
symbol                str    | (271742,)

In [9]:
# Read in the filtered ARCHS4 h5 and write out to a new h5
with h5py.File(filtered_file, "r") as fin, h5py.File('filtered_ARCHS4_TFs_4_class.h5', 'w') as fout:

    # Copy the class names into the new h5
    fin.copy("class_name", fout) 
    # Read in the gene symbol and ensembl IDs from the input h5 file
    symbols = fin["symbol"]
    ensembl_id = fin["ensembl_id"]

    # unpack the gene symbol names and decode bytes to strings
    symbols_unpack = symbols[:]
    if isinstance(symbols_unpack[0], bytes):
        symbols_unpack = [s.decode('utf-8') for s in symbols_unpack]

    # unapck the ensembl IDs and decode bytes to strings
    ensembl_unpack = ensembl_id[:]
    if isinstance(ensembl_unpack[0], bytes):
        ensembl_unpack = [s.decode('utf-8') for s in ensembl_unpack]

    # initialize the total number of genes in the input h5, an empty matched index list and the processing chunk size
    n_genes = len(symbols)
    tf_matched_indices = []
    chunk_size = 1000

    # iterate through indices of all genes in the input h5 by chunking through them
    for start_gene in range(0, n_genes, chunk_size):
        end_gene = min(start_gene + chunk_size, n_genes)
        chunk_symbols = symbols_unpack[start_gene:end_gene]

        # find the indices that match the list of known human TFs
        for i, sym in enumerate(chunk_symbols):
            if sym in tf_names:
                idx = start_gene + i
                tf_matched_indices.append(idx)

    tf_matched_indices.sort()
    print("Matched indices for TFs have been found")
    
    # Create output dataset for gene symbol in the output h5
    new_sym_dataset = fout.create_dataset(
        "symbol", 
        (len(tf_matched_indices), ),
        dtype=symbols.dtype,
        chunks=True
    )

    # Create output dataset for ensembl ID in the output h5
    new_ensembl_dataset = fout.create_dataset(
        "ensembl_id", 
        (len(tf_matched_indices), ),
        dtype=ensembl_id.dtype,
        chunks=True
    )

    # convert symbols and ensembl IDs to np arrays
    symbols_arr = np.array(symbols_unpack)
    ensembl_arr = np.array(ensembl_unpack)

    # have only the matched indices be the new symbols and ensembl ID datasets
    new_sym_dataset[...] = symbols_arr[tf_matched_indices]
    new_ensembl_dataset[...] = ensembl_arr[tf_matched_indices]

    # Get dataset info
    expr_dataset = fin['data/filtered_expression']
    n_genes, n_samples = expr_dataset.shape

    # Create output dataset
    filtered_dataset = fout.create_dataset(
        "data/filtered_expression", 
        (len(tf_matched_indices), n_samples),
        dtype=expr_dataset.dtype,
        chunks=True
    )

    # do a chunking approach to chunk through the number of samples in 1000 chunks 
    iteration = 0
    for start_sample in range(0, n_samples, chunk_size):
        end_sample = min(start_sample + chunk_size, n_samples)
        data_chunk = expr_dataset[tf_matched_indices, start_sample:end_sample]
        filtered_dataset[:, start_sample:end_sample] = data_chunk
        print("Iteration " + str(iteration)+ " is done.")
        iteration += 1

Matched indices for TFs have been found
Iteration 0 is done.
Iteration 1 is done.
Iteration 2 is done.
Iteration 3 is done.
Iteration 4 is done.
Iteration 5 is done.
Iteration 6 is done.
Iteration 7 is done.
Iteration 8 is done.
Iteration 9 is done.
Iteration 10 is done.

In [10]:
filtered_TFs_file = "/scratch/by2372/pipeline/ARCHS4_Macrophages/Source_name_4_class/filtered_ARCHS4_TFs_4_class.h5"
a4.ls(filtered_TFs_file)

class_name            str    | (10775,)
data
│ filtered_expression   float32 | (13146, 10775)
ensembl_id            str    | (13146,)
symbol                str    | (13146,)

# The code below will create training and testing datasets

In [11]:
def chunk_samples(chunk_size, n_samples, n_genes, output, input):
    iteration = 0
    for start_sample in range(0, n_samples, chunk_size):
        end_sample = min(start_sample + chunk_size, n_samples)

        for start_gene in range(0, n_genes, chunk_size):
            end_gene = min(start_gene + chunk_size, n_genes)

            # Read a chunk of the input matrix
            data_chunk = input[start_sample:end_sample, start_gene:end_gene]

            # Write the chunk to the output dataset
            output[start_sample:end_sample, start_gene:end_gene] = data_chunk

        print("Iteration " + str(iteration) + " (samples " + str(start_sample) + "-" + str(end_sample) + ") is done.")
        iteration += 1

In [12]:
def chunk_class(chunk_size,n_samples,output,input):
    iteration = 0
    for start_sample in range(0, n_samples, chunk_size):
        end_sample = min(start_sample + chunk_size, n_samples)
        data_chunk = input[start_sample:end_sample]
        output[start_sample:end_sample] = data_chunk
        print("Iteration " + str(iteration)+ " is done.")
        iteration += 1

In [13]:
# Make Rows be the samples and the columns be the transcripts
# make it into a data frame and export as H5
with h5py.File(filtered_TFs_file, "r") as fin, h5py.File('filtered_training_4_class.h5', 'w') as ftrain, h5py.File('filtered_testing_4_class.h5', 'w') as ftest:

    # Navigate to the metadata group for class names, gene symbols, and ensembl ID
    class_name_ds = fin['class_name']
    ensembl_id = fin["ensembl_id"]
    symbols = fin["symbol"]

    # Read all names and decode bytes to strings
    symbols_unpack = symbols[:]
    if isinstance(symbols_unpack[0], bytes):
        symbols_unpack = [s.decode('utf-8') for s in symbols_unpack]

    # Read all names and decode bytes to strings
    class_names = class_name_ds[:]
    if isinstance(class_names[0], bytes):
        class_names = [s.decode('utf-8') for s in class_names]

    ensembl_unpack = ensembl_id[:]
    if isinstance(ensembl_unpack[0], bytes):
        ensembl_unpack = [s.decode('utf-8') for s in ensembl_unpack]

    # Navigate to the metadata group for the expression data
    expression = fin["data/filtered_expression"]

    # Transpose expression data so that rows are samples and columns are transcripts
    expression_data = expression[:, :] 
    expression_data = expression_data.T
    print("Expression data has been transposed\n")

    # Make the transcript ID be the symbol _ ensembl ID
    transcript_ID = []
    for idx, sym in enumerate(symbols_unpack):
        ID = sym + "_" + ensembl_unpack[idx]
        transcript_ID.append(ID)

    filtered_df = pd.DataFrame(expression_data,index = class_names, columns = transcript_ID)
    filtered_df['cell_identity'] = class_names

    # Count occurrences of each cell_identity
    cell_identity_counts = filtered_df['cell_identity'].value_counts()
    print(cell_identity_counts)

    # Create a boolean mask to filter rows with cell_identity occurring more than once
    mask = filtered_df['cell_identity'].isin(cell_identity_counts[cell_identity_counts > 1].index)

    # Filter the DataFrame using the mask
    filtered_df = filtered_df[mask]

    # Seperate the ensmbl ids from the cell_identity column
    TFs = filtered_df.columns.drop(['cell_identity'])

    # Set predictors and predicted
    X = np.array(filtered_df[TFs])
    y = np.array(filtered_df['cell_identity'])

    # Train - test split with stratification and shuffling
    ### THIS LOADS IN THE WHOLE H5 FILE TO SPLIT
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=5, stratify=y,shuffle = True)

    # Create output dataset
    X_train_out = ftrain.create_dataset(
        "expression", 
        (X_train.shape[0], X_train.shape[1]),
        dtype=expression.dtype,
        chunks=True
    )
    print("Starting X Train output into H5")
    chunk_samples(1000,X_train.shape[0],X_train.shape[1],X_train_out,X_train)
    print("X Train output successfully")

    y_train_out = ftrain.create_dataset(
        "label",
        len(y_train),
        dtype=h5py.string_dtype(encoding='utf-8'),
        chunks = True
    )
    print("Starting y train output into H5")
    chunk_class(1000,len(y_train),y_train_out,y_train)
    print("y Train output successfully")

    TF_ID_out = ftrain.create_dataset(
        "TF_ID",
        len(transcript_ID),
        dtype=h5py.string_dtype(encoding='utf-8'),
        chunks = True
    )
    print("Starting TF IDs output into training H5")
    chunk_class(1000,len(transcript_ID),TF_ID_out,transcript_ID)
    print("TF ID output successfully")
    
    ###export X_test, y_test with Transcript_ID or TFs to an h5
    
    X_test_out = ftest.create_dataset(
        "expression", 
        (X_test.shape[0], X_test.shape[1]),
        dtype=expression.dtype,
        chunks=True
    )
    print("Starting X Test output into H5")
    chunk_samples(1000,X_test.shape[0],X_test.shape[1],X_test_out,X_test)
    print("X test output successfully")

    y_test_out = ftest.create_dataset(
        "label",
        len(y_test),
        dtype=h5py.string_dtype(encoding='utf-8'),
        chunks = True
    )
    print("Starting y test output into H5")
    chunk_class(1000,len(y_test),y_test_out,y_test)
    print("y test output successfully")

    TF_ID_out = ftest.create_dataset(
        "TF_ID",
        len(transcript_ID),
        dtype=h5py.string_dtype(encoding='utf-8'),
        chunks = True
    )
    print("Starting TF IDs output into testing H5")
    chunk_class(1000,len(transcript_ID),TF_ID_out,transcript_ID)
    print("TF ID output successfully")

Expression data has been transposed

cell_identity
Monocyte      5497
Macrophage    4183
Microglia      672
other          423
Name: count, dtype: int64
Starting X Train output into H5
Iteration 0 (samples 0-1000) is done.
Iteration 1 (samples 1000-2000) is done.
Iteration 2 (samples 2000-3000) is done.
Iteration 3 (samples 3000-4000) is done.
Iteration 4 (samples 4000-5000) is done.
Iteration 5 (samples 5000-6000) is done.
Iteration 6 (samples 6000-7000) is done.
Iteration 7 (samples 7000-8000) is done.
Iteration 8 (samples 8000-8081) is done.
X Train output successfully
Starting y train output into H5
Iteration 0 is done.
Iteration 1 is done.
Iteration 2 is done.
Iteration 3 is done.
Iteration 4 is done.
Iteration 5 is done.
Iteration 6 is done.
Iteration 7 is done.
Iteration 8 is done.
y Train output successfully
Starting TF IDs output into training H5
Iteration 0 is done.
Iteration 1 is done.
Iteration 2 is done.
Iteration 3 is done.
Iteration 4 is done.
Iteration 5 is done.
Iteration 6 is done.
Iteration 7 is done.
Iteration 8 is done.
Iteration 9 is done.
Iteration 10 is done.
Iteration 11 is done.
Iteration 12 is done.
Iteration 13 is done.
TF ID output successfully
Starting X Test output into H5
Iteration 0 (samples 0-1000) is done.
Iteration 1 (samples 1000-2000) is done.
Iteration 2 (samples 2000-2694) is done.
X test output successfully
Starting y test output into H5
Iteration 0 is done.
Iteration 1 is done.
Iteration 2 is done.
y test output successfully
Starting TF IDs output into testing H5
Iteration 0 is done.
Iteration 1 is done.
Iteration 2 is done.
Iteration 3 is done.
Iteration 4 is done.
Iteration 5 is done.
Iteration 6 is done.
Iteration 7 is done.
Iteration 8 is done.
Iteration 9 is done.
Iteration 10 is done.
Iteration 11 is done.
Iteration 12 is done.
Iteration 13 is done.
TF ID output successfully

In [14]:
train_file = "/scratch/by2372/pipeline/ARCHS4_Macrophages/Source_name_4_class/filtered_training_4_class.h5"
#redownload the most recent transcript file
a4.ls(train_file)

TF_ID                 str    | (13146,)
expression            float32 | (8081, 13146)
label                 str    | (8081,)

In [15]:
test_file = "/scratch/by2372/pipeline/ARCHS4_Macrophages/Source_name_4_class/filtered_testing_4_class.h5"
#redownload the most recent transcript file
a4.ls(test_file)

TF_ID                 str    | (13146,)
expression            float32 | (2694, 13146)
label                 str    | (2694,)

In [16]:
pd.Series(y_train).value_counts()

Monocyte      4123
Macrophage    3137
Microglia      504
other          317
Name: count, dtype: int64

In [17]:
pd.Series(y_test).value_counts()

Monocyte      1374
Macrophage    1046
Microglia      168
other          106
Name: count, dtype: int64

### Load in training and testing data here

In [2]:
f_train = h5py.File("/scratch/by2372/pipeline/ARCHS4_Macrophages/Source_name_4_class/filtered_training_4_class.h5", 'r')
expression_train = f_train['expression'][...]
label_train = f_train['label'][...]
f_train.close()
f_test = h5py.File("/scratch/by2372/pipeline/ARCHS4_Macrophages/Source_name_4_class/filtered_testing_4_class.h5", 'r')
expression_test = f_test['expression'][...]
label_test = f_test['label'][...]

TFs = f_test['TF_ID'][...]

# Read all names and decode bytes to strings
if isinstance(label_train[0], bytes):
    label_train = [s.decode('utf-8') for s in label_train]

# Read all names and decode bytes to strings
if isinstance(label_test[0], bytes):
    label_test = [s.decode('utf-8') for s in label_test]

# Read all names and decode bytes to strings
if isinstance(TFs[0], bytes):
    TFs = [s.decode('utf-8') for s in TFs]

f_test.close()

### Random Oversampler on Training Data

In [3]:
from imblearn.over_sampling import RandomOverSampler
from collections import Counter

ros = RandomOverSampler(random_state=42)
expression_ros, label_ros = ros.fit_resample(expression_train,label_train)

print("Original class distribution:", Counter(label_train))
print("Resampled class distribution:", Counter(label_ros))

Original class distribution: Counter({'Monocyte': 4123, 'Macrophage': 3137, 'Microglia': 504, 'other': 317})
Resampled class distribution: Counter({'Monocyte': 4123, 'Macrophage': 4123, 'Microglia': 4123, 'other': 4123})

### SMOTE on Training Data

In [4]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=0,k_neighbors = 1)
expression_SMOTE, label_SMOTE = smote.fit_resample(expression_train,label_train)

print("Original class distribution:", Counter(label_train))
print("Resampled class distribution:", Counter(label_SMOTE))

Original class distribution: Counter({'Monocyte': 4123, 'Macrophage': 3137, 'Microglia': 504, 'other': 317})
Resampled class distribution: Counter({'Monocyte': 4123, 'Macrophage': 4123, 'Microglia': 4123, 'other': 4123})

### BLSMOTE on Training Data

In [5]:
from imblearn.over_sampling import BorderlineSMOTE
from collections import Counter

BLsmote = BorderlineSMOTE(random_state=1,k_neighbors = 1)
expression_BLSMOTE, label_BLSMOTE = BLsmote.fit_resample(expression_train,label_train)

print("Original class distribution:", Counter(label_train))
print("Resampled class distribution:", Counter(label_BLSMOTE))

Original class distribution: Counter({'Monocyte': 4123, 'Macrophage': 3137, 'Microglia': 504, 'other': 317})
Resampled class distribution: Counter({'Monocyte': 4123, 'Macrophage': 4123, 'Microglia': 4123, 'other': 4123})

# Below is the code for neural network training

In [2]:
from tensorflow import keras
from sklearn.preprocessing import LabelEncoder
import tensorflow as tef
from keras import optimizers
from keras import losses
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA, KernelPCA
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score
from sklearn.preprocessing import label_binarize
from sklearn.metrics import (auc, roc_curve, roc_auc_score)
from tensorflow.keras.models import load_model
import os

2026-03-18 00:26:26.147884: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-18 00:26:29.770467: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 AVX512_FP16 AVX_VNNI AMX_TILE AMX_INT8 AMX_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-03-18 00:26:40.392075: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

In [7]:
def NN_training(X_train,y_train,X_test,y_test,TFS,name):

    keras.utils.set_random_seed(10)   
    
    num_unique_y = len(set(y_train))

    le = LabelEncoder()
    
    # Fit on training labels (strings) and transform them to integers
    label_train_int = le.fit_transform(y_train)
    
    # Use the same encoder to transform test labels
    label_test_int = le.transform(y_test)
    
    # Best model in magnussen paper was 2 layers of 250 nodes
    model = keras.Sequential([
        keras.layers.Input(shape=(len(TFs),)),  # there are 13146 TFs
        keras.layers.Dense(250, activation='elu'),
        keras.layers.Dense(250, activation='elu'),
        keras.layers.Dense(num_unique_y, activation='softmax')  # For multiclass classification
    ])

    callback = keras.callbacks.EarlyStopping(monitor='val_loss', patience = 3)
    
    adam = optimizers.Adam(
        learning_rate=0.001,
        beta_1=0.9,
        beta_2=0.999,
        weight_decay=0.01  # replaces old `decay`
    )
    model.compile(loss='sparse_categorical_crossentropy',optimizer=adam,metrics=['accuracy'], )
    model.fit(X_train, label_train_int, batch_size=50, epochs=100, verbose=1, validation_split = 0.1, callbacks = [callback])

    model.save("/scratch/by2372/pipeline/ARCHS4_Macrophages/Trained_NN/" + name + "_trained_NN.keras")

    np.save("/scratch/by2372/pipeline/ARCHS4_Macrophages/Trained_NN/" + name + "_class_names.npy", le.classes_)

    loss, accuracy = model.evaluate(X_test, label_test_int, verbose=1)

    # Predictions on test set
    y_prob = model.predict(X_test)
    y_pred = np.argmax(y_prob, axis=1)

    # Calculate F1 Metrics
    f1_macro = f1_score(label_test_int, y_pred, average='macro')
    f1_weighted = f1_score(label_test_int, y_pred, average='weighted')
    f1_micro = f1_score(label_test_int,y_pred,average = 'micro')

     # binarize the classes
    cell_classes = np.unique(np.concatenate((label_train_int, label_test_int)))
    y_test_bin = label_binarize(label_test_int, classes=cell_classes)

    fpr = dict()
    tpr = dict()
    roc_auc = dict()
    roc_auc_labeled = dict()

    # One vs. rest AUC calculation for multiclass data
    for i in range(len(cell_classes)):
        cur_class = cell_classes[i]
        fpr[cur_class], tpr[cur_class], _ = roc_curve(y_test_bin[:, i], y_prob[:, i])
        roc_auc[cur_class] = auc(fpr[cur_class], tpr[cur_class])
        # Inverse transform the label encoder to get the class label once again
        class_label = le.inverse_transform([cur_class])[0]
        roc_auc_labeled[class_label] = roc_auc[cur_class]
        print(f"AUC for class {cur_class}: {roc_auc[cur_class]:.2f}")

    # compute micro-average ROC curve and ROC area
    fpr["micro"], tpr["micro"],_=roc_curve(y_test_bin.ravel(),y_prob.ravel())
    roc_auc_labeled["micro"] = auc(fpr["micro"],tpr["micro"])   

    return {
    "f1_macro": f1_macro,
    "f1_weighted": f1_weighted,
    "f1_micro": f1_micro,
    "roc_auc_micro": roc_auc_labeled["micro"],
    "roc_auc_per_class": roc_auc_labeled,
    "loss" : loss,
    "accuracy" : accuracy
    }

In [8]:
unbal_metrics = NN_training(expression_train,label_train,expression_test,label_test,TFs,"unbalanced_4_class")

2026-03-17 00:19:35.832810: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

Epoch 1/100
146/146 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.8769 - loss: 1.7023 - val_accuracy: 0.9234 - val_loss: 0.6159
Epoch 2/100
146/146 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.9586 - loss: 0.1989 - val_accuracy: 0.9320 - val_loss: 0.5231
Epoch 3/100
146/146 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9629 - loss: 0.1881 - val_accuracy: 0.9654 - val_loss: 0.2159
Epoch 4/100
146/146 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.9728 - loss: 0.1282 - val_accuracy: 0.9592 - val_loss: 0.2414
Epoch 5/100
146/146 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9824 - loss: 0.0815 - val_accuracy: 0.9543 - val_loss: 0.3616
Epoch 6/100
146/146 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.9904 - loss: 0.0407 - val_accuracy: 0.9703 - val_loss: 0.1786
Epoch 7/100
146/146 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.9897 - loss: 0.0482 - val_accuracy: 0.9728 - val_loss: 0.2654
Epoch 8/100
146/146 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9867 - loss: 0.0543 - val_accuracy: 0.9691 - val_loss: 0.1577
Epoch 9/100
146/146 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9838 - loss: 0.1019 - val_accuracy: 0.9716 - val_loss: 0.1519
Epoch 10/100
146/146 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.9901 - loss: 0.0473 - val_accuracy: 0.9728 - val_loss: 0.2655
Epoch 11/100
146/146 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.9829 - loss: 0.0972 - val_accuracy: 0.9295 - val_loss: 0.3222
Epoch 12/100
146/146 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.9860 - loss: 0.0666 - val_accuracy: 0.9654 - val_loss: 0.2536
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9744 - loss: 0.2555
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
AUC for class 0: 1.00
AUC for class 1: 1.00
AUC for class 2: 0.99
AUC for class 3: 0.98

In [9]:
unbal_metrics

{'f1_macro': 0.9622212889791782,
 'f1_weighted': 0.9743651759502449,
 'f1_micro': 0.9743875278396437,
 'roc_auc_micro': 0.9969425305981178,
 'roc_auc_per_class': {np.str_('Macrophage'): 0.99573821446472,
  np.str_('Microglia'): 0.999615899408061,
  np.str_('Monocyte'): 0.994777744695867,
  np.str_('other'): 0.9832827855705579,
  'micro': 0.9969425305981178},
 'loss': 0.25549188256263733,
 'accuracy': 0.974387526512146}

In [10]:
ROS_metrics = NN_training(expression_ros,label_ros,expression_test,label_test,TFs,"ROS_4_class")

Epoch 1/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9198 - loss: 0.7974 - val_accuracy: 0.9952 - val_loss: 0.0502
Epoch 2/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9691 - loss: 0.1837 - val_accuracy: 1.0000 - val_loss: 0.0067
Epoch 3/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9870 - loss: 0.0584 - val_accuracy: 1.0000 - val_loss: 0.0042
Epoch 4/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9922 - loss: 0.0351 - val_accuracy: 1.0000 - val_loss: 0.0058
Epoch 5/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9929 - loss: 0.0330 - val_accuracy: 0.9745 - val_loss: 0.0519
Epoch 6/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9755 - loss: 0.1680 - val_accuracy: 0.9933 - val_loss: 0.0554
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9733 - loss: 0.3570
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
AUC for class 0: 0.99
AUC for class 1: 1.00
AUC for class 2: 0.99
AUC for class 3: 0.98

In [11]:
ROS_metrics

{'f1_macro': 0.9695628857220243,
 'f1_weighted': 0.9732093006265568,
 'f1_micro': 0.9732739420935412,
 'roc_auc_micro': 0.9960527091741719,
 'roc_auc_per_class': {np.str_('Macrophage'): 0.9945922051643802,
  np.str_('Microglia'): 0.9999104550767257,
  np.str_('Monocyte'): 0.9928124035110935,
  np.str_('other'): 0.9790469802572104,
  'micro': 0.9960527091741719},
 'loss': 0.35704711079597473,
 'accuracy': 0.9732739329338074}

In [12]:
SMOTE_metrics = NN_training(expression_SMOTE,label_SMOTE,expression_test,label_test,TFs,"SMOTE_4_class")

Epoch 1/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9287 - loss: 0.7324 - val_accuracy: 1.0000 - val_loss: 0.0107
Epoch 2/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9746 - loss: 0.1761 - val_accuracy: 0.9442 - val_loss: 0.1681
Epoch 3/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9864 - loss: 0.0630 - val_accuracy: 1.0000 - val_loss: 0.0016
Epoch 4/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9795 - loss: 0.1265 - val_accuracy: 1.0000 - val_loss: 0.0038
Epoch 5/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9825 - loss: 0.1356 - val_accuracy: 1.0000 - val_loss: 0.0032
Epoch 6/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9912 - loss: 0.0466 - val_accuracy: 1.0000 - val_loss: 6.4603e-04
Epoch 7/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9969 - loss: 0.0112 - val_accuracy: 1.0000 - val_loss: 4.6807e-04
Epoch 8/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9966 - loss: 0.0150 - val_accuracy: 1.0000 - val_loss: 2.8695e-04
Epoch 9/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9830 - loss: 0.0870 - val_accuracy: 1.0000 - val_loss: 0.0010
Epoch 10/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9905 - loss: 0.0692 - val_accuracy: 1.0000 - val_loss: 2.5574e-04
Epoch 11/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9907 - loss: 0.0739 - val_accuracy: 1.0000 - val_loss: 2.2973e-04
Epoch 12/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9970 - loss: 0.0130 - val_accuracy: 1.0000 - val_loss: 2.1350e-04
Epoch 13/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9992 - loss: 0.0053 - val_accuracy: 1.0000 - val_loss: 2.4863e-04
Epoch 14/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9999 - loss: 8.2072e-04 - val_accuracy: 1.0000 - val_loss: 2.0867e-04
Epoch 15/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9999 - loss: 5.1870e-04 - val_accuracy: 1.0000 - val_loss: 2.0008e-04
Epoch 16/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9999 - loss: 4.3514e-04 - val_accuracy: 1.0000 - val_loss: 1.8731e-04
Epoch 17/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9999 - loss: 4.0179e-04 - val_accuracy: 1.0000 - val_loss: 1.7780e-04
Epoch 18/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9999 - loss: 3.8500e-04 - val_accuracy: 1.0000 - val_loss: 1.6975e-04
Epoch 19/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9999 - loss: 3.7802e-04 - val_accuracy: 1.0000 - val_loss: 1.6221e-04
Epoch 20/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9999 - loss: 3.7350e-04 - val_accuracy: 1.0000 - val_loss: 1.5500e-04
Epoch 21/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9999 - loss: 3.7052e-04 - val_accuracy: 1.0000 - val_loss: 1.4808e-04
Epoch 22/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9999 - loss: 3.6862e-04 - val_accuracy: 1.0000 - val_loss: 1.4149e-04
Epoch 23/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9999 - loss: 3.6751e-04 - val_accuracy: 1.0000 - val_loss: 1.3525e-04
Epoch 24/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9999 - loss: 3.6706e-04 - val_accuracy: 1.0000 - val_loss: 1.2939e-04
Epoch 25/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9999 - loss: 3.6711e-04 - val_accuracy: 1.0000 - val_loss: 1.2398e-04
Epoch 26/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9999 - loss: 3.6756e-04 - val_accuracy: 1.0000 - val_loss: 1.1903e-04
Epoch 27/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9999 - loss: 3.6830e-04 - val_accuracy: 1.0000 - val_loss: 1.1456e-04
Epoch 28/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9999 - loss: 3.6921e-04 - val_accuracy: 1.0000 - val_loss: 1.1056e-04
Epoch 29/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9999 - loss: 3.7056e-04 - val_accuracy: 1.0000 - val_loss: 1.0702e-04
Epoch 30/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9999 - loss: 3.7146e-04 - val_accuracy: 1.0000 - val_loss: 1.0386e-04
Epoch 31/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9999 - loss: 3.7225e-04 - val_accuracy: 1.0000 - val_loss: 1.0115e-04
Epoch 32/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9999 - loss: 3.7330e-04 - val_accuracy: 1.0000 - val_loss: 9.8830e-05
Epoch 33/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9999 - loss: 3.7431e-04 - val_accuracy: 1.0000 - val_loss: 9.6886e-05
Epoch 34/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9999 - loss: 3.7524e-04 - val_accuracy: 1.0000 - val_loss: 9.5331e-05
Epoch 35/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9999 - loss: 3.7601e-04 - val_accuracy: 1.0000 - val_loss: 9.4037e-05
Epoch 36/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9999 - loss: 3.7672e-04 - val_accuracy: 1.0000 - val_loss: 9.3245e-05
Epoch 37/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9999 - loss: 3.7715e-04 - val_accuracy: 1.0000 - val_loss: 9.2649e-05
Epoch 38/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9999 - loss: 3.7742e-04 - val_accuracy: 1.0000 - val_loss: 9.2086e-05
Epoch 39/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9999 - loss: 3.7797e-04 - val_accuracy: 1.0000 - val_loss: 9.2248e-05
Epoch 40/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9999 - loss: 3.7772e-04 - val_accuracy: 1.0000 - val_loss: 9.2737e-05
Epoch 41/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9999 - loss: 3.7743e-04 - val_accuracy: 1.0000 - val_loss: 9.3241e-05
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9892 - loss: 0.3296
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
AUC for class 0: 1.00
AUC for class 1: 1.00
AUC for class 2: 1.00
AUC for class 3: 0.99

In [13]:
SMOTE_metrics

{'f1_macro': 0.9845032708690801,
 'f1_weighted': 0.9892172800169263,
 'f1_micro': 0.9892353377876764,
 'roc_auc_micro': 0.9969269837543059,
 'roc_auc_per_class': {np.str_('Macrophage'): 0.9951752167294734,
  np.str_('Microglia'): 1.0,
  np.str_('Monocyte'): 0.9956304309470247,
  np.str_('other'): 0.9862245195532354,
  'micro': 0.9969269837543059},
 'loss': 0.32955214381217957,
 'accuracy': 0.9892353415489197}

In [15]:
BLSMOTE_metrics = NN_training(expression_BLSMOTE,label_BLSMOTE,expression_test,label_test,TFs,"BLSMOTE_4_class")

Epoch 1/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9280 - loss: 0.7257 - val_accuracy: 1.0000 - val_loss: 0.0205
Epoch 2/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9800 - loss: 0.0994 - val_accuracy: 1.0000 - val_loss: 0.0071
Epoch 3/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9719 - loss: 0.1973 - val_accuracy: 1.0000 - val_loss: 0.0025
Epoch 4/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9858 - loss: 0.0642 - val_accuracy: 1.0000 - val_loss: 0.0015
Epoch 5/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9923 - loss: 0.0324 - val_accuracy: 1.0000 - val_loss: 0.0011
Epoch 6/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9941 - loss: 0.0252 - val_accuracy: 1.0000 - val_loss: 8.4307e-04
Epoch 7/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9980 - loss: 0.0089 - val_accuracy: 0.9976 - val_loss: 0.0057
Epoch 8/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9755 - loss: 0.1897 - val_accuracy: 0.9873 - val_loss: 0.0331
Epoch 9/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9906 - loss: 0.1034 - val_accuracy: 1.0000 - val_loss: 6.6324e-04
Epoch 10/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9958 - loss: 0.0194 - val_accuracy: 1.0000 - val_loss: 5.7449e-04
Epoch 11/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9980 - loss: 0.0149 - val_accuracy: 1.0000 - val_loss: 5.7370e-04
Epoch 12/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9970 - loss: 0.0140 - val_accuracy: 1.0000 - val_loss: 5.8690e-04
Epoch 13/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9988 - loss: 0.0038 - val_accuracy: 1.0000 - val_loss: 5.2050e-04
Epoch 14/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9982 - loss: 0.0065 - val_accuracy: 1.0000 - val_loss: 5.0898e-04
Epoch 15/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9875 - loss: 0.0906 - val_accuracy: 1.0000 - val_loss: 4.9946e-04
Epoch 16/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9962 - loss: 0.0402 - val_accuracy: 1.0000 - val_loss: 5.0988e-04
Epoch 17/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9912 - loss: 0.0369 - val_accuracy: 1.0000 - val_loss: 6.2315e-04
Epoch 18/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9974 - loss: 0.0132 - val_accuracy: 1.0000 - val_loss: 4.5331e-04
Epoch 19/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9991 - loss: 0.0030 - val_accuracy: 1.0000 - val_loss: 4.1559e-04
Epoch 20/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9999 - loss: 7.8356e-04 - val_accuracy: 1.0000 - val_loss: 3.9990e-04
Epoch 21/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9999 - loss: 5.0671e-04 - val_accuracy: 1.0000 - val_loss: 3.8266e-04
Epoch 22/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9999 - loss: 4.9364e-04 - val_accuracy: 1.0000 - val_loss: 3.6360e-04
Epoch 23/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9999 - loss: 4.8623e-04 - val_accuracy: 1.0000 - val_loss: 3.4465e-04
Epoch 24/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9999 - loss: 4.8208e-04 - val_accuracy: 1.0000 - val_loss: 3.2644e-04
Epoch 25/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9999 - loss: 4.7987e-04 - val_accuracy: 1.0000 - val_loss: 3.0928e-04
Epoch 26/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9999 - loss: 4.7887e-04 - val_accuracy: 1.0000 - val_loss: 2.9340e-04
Epoch 27/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9999 - loss: 4.7875e-04 - val_accuracy: 1.0000 - val_loss: 2.7889e-04
Epoch 28/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9999 - loss: 4.7921e-04 - val_accuracy: 1.0000 - val_loss: 2.6585e-04
Epoch 29/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9999 - loss: 4.8005e-04 - val_accuracy: 1.0000 - val_loss: 2.5427e-04
Epoch 30/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9999 - loss: 4.8110e-04 - val_accuracy: 1.0000 - val_loss: 2.4415e-04
Epoch 31/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9999 - loss: 4.8224e-04 - val_accuracy: 1.0000 - val_loss: 2.3545e-04
Epoch 32/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9999 - loss: 4.8337e-04 - val_accuracy: 1.0000 - val_loss: 2.2813e-04
Epoch 33/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9999 - loss: 4.8442e-04 - val_accuracy: 1.0000 - val_loss: 2.2209e-04
Epoch 34/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9999 - loss: 4.8532e-04 - val_accuracy: 1.0000 - val_loss: 2.1723e-04
Epoch 35/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9999 - loss: 4.8606e-04 - val_accuracy: 1.0000 - val_loss: 2.1346e-04
Epoch 36/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9999 - loss: 4.8662e-04 - val_accuracy: 1.0000 - val_loss: 2.1060e-04
Epoch 37/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9999 - loss: 4.8702e-04 - val_accuracy: 1.0000 - val_loss: 2.0855e-04
Epoch 38/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9999 - loss: 4.8730e-04 - val_accuracy: 1.0000 - val_loss: 2.0729e-04
Epoch 39/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9999 - loss: 4.8733e-04 - val_accuracy: 1.0000 - val_loss: 2.0665e-04
Epoch 40/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9999 - loss: 4.8715e-04 - val_accuracy: 1.0000 - val_loss: 2.0596e-04
Epoch 41/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9999 - loss: 4.8730e-04 - val_accuracy: 1.0000 - val_loss: 2.0677e-04
Epoch 42/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9999 - loss: 4.8664e-04 - val_accuracy: 1.0000 - val_loss: 2.0797e-04
Epoch 43/100
297/297 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9999 - loss: 4.8602e-04 - val_accuracy: 1.0000 - val_loss: 2.0953e-04
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9844 - loss: 0.4860
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
AUC for class 0: 0.99
AUC for class 1: 1.00
AUC for class 2: 0.99
AUC for class 3: 0.98

In [16]:
BLSMOTE_metrics

{'f1_macro': 0.9766960117104666,
 'f1_weighted': 0.9843984329142723,
 'f1_micro': 0.9844097995545658,
 'roc_auc_micro': 0.9960115111862872,
 'roc_auc_per_class': {np.str_('Macrophage'): 0.9941936689004809,
  np.str_('Microglia'): 0.9997843852505374,
  np.str_('Monocyte'): 0.9948116536544485,
  np.str_('other'): 0.9841376017030709,
  'micro': 0.9960115111862872},
 'loss': 0.4859751760959625,
 'accuracy': 0.9844098091125488}

# Node Light up Test is below

In [3]:
# Import expression data and transcript data from filtered h5 file
filtered_file_tf = h5py.File("/scratch/by2372/pipeline/ARCHS4_Macrophages/Source_name_4_class/filtered_ARCHS4_TFs_4_class.h5", 'r')
ensembl_id = filtered_file_tf['ensembl_id'][...]
symbol = filtered_file_tf['symbol'][...]
expression = filtered_file_tf['data/filtered_expression'][...]
filtered_file_tf.close()

# Read all names and decode bytes to strings
if isinstance(ensembl_id[0], bytes):
    ensembl_id = [s.decode('utf-8') for s in ensembl_id]

# Read all names and decode bytes to strings
if isinstance(symbol[0], bytes):
    symbol = [s.decode('utf-8') for s in symbol]

# Make the transcript ID be the symbol _ ensembl ID
transcript_ID = []
for idx, sym in enumerate(symbol):
    ID = sym + "_" + ensembl_id[idx]
    transcript_ID.append(ID)

In [4]:
expression.shape

(13146, 10775)

In [5]:
len(transcript_ID)

13146

In [6]:
class_names = np.load('/scratch/by2372/pipeline/ARCHS4_Macrophages/Trained_NN/unbalanced_4_class_class_names.npy')
class_names

array(['Macrophage', 'Microglia', 'Monocyte', 'other'], dtype='<U10')

### Implement the Node Light up technique as a function

In [11]:
def node_light_up(model_name,tf_names,express_mat,cell_type):
    # load train keras model
    model = load_model('/scratch/by2372/pipeline/ARCHS4_Macrophages/Trained_NN/' + model_name + '_trained_NN.keras')
    # create square matrix of zeros. Number of rows and cols is number of TFs
    inp = np.zeros((model.input_shape[1],model.input_shape[1])).T
    # Import cell class names 
    class_names = np.load('/scratch/by2372/pipeline/ARCHS4_Macrophages/Trained_NN/' + model_name + '_class_names.npy')

    cell_type_index = np.where(class_names == cell_type)[0][0]
    # Generate baseline TF expression values for the inp square matrix
    tf_data = pd.DataFrame(express_mat).iloc[:,:].mean(1)
    for i in range(inp.shape[1]):
        inp[i, :] = tf_data.values
    # Generate doubled and halved expression for TFs. Only diagonals of the baseline square matrix is doubled or halved
    half = inp.copy()
    double = inp.copy()
    half[np.eye(half.shape[0]).astype(bool)] = 0.5*half[np.eye(half.shape[0]).astype(bool)]
    double[np.eye(double.shape[0]).astype(bool)] = 2*double[np.eye(double.shape[0]).astype(bool)]

    background_pred = model.predict(inp)
    background_idx = np.argmax(background_pred, axis=1)
    background_labels = class_names[background_idx]
    
    double_pred = model.predict(double)
    double_idx = np.argmax(double_pred, axis=1)
    double_labels = class_names[double_idx]
    
    half_pred = model.predict(half)
    half_idx = np.argmax(half_pred, axis=1)
    half_labels = class_names[half_idx]

    double_background = double_pred[:,cell_type_index] - background_pred[:,cell_type_index]
    half_background = half_pred[:,cell_type_index] - background_pred[:,cell_type_index]

    score = (double_background - half_background) / 2
    score = pd.DataFrame(score, index=tf_names, columns=[cell_type])
    score_sorted = score.sort_values(by=cell_type, ascending=True)
    
    # 7th column is for macrophages classification
    #double_background = (double_pred[:,cell_type_index] - background_pred[:,cell_type_index]) / background_pred[:,cell_type_index]
    #double_background = pd.DataFrame(double_background)
    #double_background.index = tf_names
    #double_background.columns = [cell_type]
    #double_background_sorted = double_background.sort_values(by = cell_type, ascending=True)
    
    #half_background = (half_pred[:,cell_type_index] - background_pred[:,cell_type_index]) / background_pred[:,cell_type_index]
    #half_background = pd.DataFrame(half_background)
    #half_background.index = tf_names
    #half_background.columns = [cell_type]
    #half_background_sorted = half_background.sort_values(by = cell_type, ascending=True)

    return score_sorted

In [13]:
unbalanced_macrophages = node_light_up("unbalanced_4_class",transcript_ID,expression,"Macrophage")

/state/partition1/job-4470344/ipykernel_724939/1994595373.py:11: Pandas4Warning: Starting with pandas version 4.0 all arguments of mean will be keyword-only.
  tf_data = pd.DataFrame(express_mat).iloc[:,:].mean(1)

411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [14]:
unbalanced_macrophages.head(n=20)

                        Macrophage
JUNB_ENST00000302754     -0.462145
SPI1_ENST00000378538     -0.313338
KLF6_ENST00000542957     -0.269514
CEBPB_ENST00000303004    -0.259794
NME2_ENST00000512737     -0.244788
ATF4_ENST00000674920     -0.231864
STAT6_ENST00000300134    -0.189392
KMT2A_ENST00000648029    -0.189383
FOS_ENST00000303562      -0.145038
FOS_ENST00000556324      -0.142716
KLF6_ENST00000497571     -0.128559
CSRNP1_ENST00000273153   -0.124108
JUND_ENST00000252818     -0.123304
TRAFD1_ENST00000412615   -0.117957
FOS_ENST00000554617      -0.109378
DRAP1_ENST00000312515    -0.097810
LYL1_ENST00000264824     -0.091179
ZNF302_ENST00000507959   -0.089246
NFKB1_ENST00000652569    -0.087036
FOSL2_ENST00000264716    -0.086318

In [15]:
for idx, t in enumerate(unbalanced_macrophages.index):
    if "ZNF385A" in str(t):
        print(idx)

149
257
368
557
2144
2196
2437
2812
9036
10781
11898
12270
12992
13056
13097

In [16]:
unbalanced_microglia = node_light_up("unbalanced_4_class",transcript_ID,expression,"Microglia")

/state/partition1/job-4470344/ipykernel_724939/1994595373.py:11: Pandas4Warning: Starting with pandas version 4.0 all arguments of mean will be keyword-only.
  tf_data = pd.DataFrame(express_mat).iloc[:,:].mean(1)

411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [17]:
unbalanced_microglia.head(n=20)

                            Microglia
YBX1_ENST00000436427    -5.651181e-11
JUNB_ENST00000302754    -4.772771e-11
SPI1_ENST00000227163    -3.108271e-11
XBP1_ENST00000216037    -2.464278e-11
CEBPD_ENST00000408965   -2.393846e-11
MAFB_ENST00000373313    -2.115332e-11
FOS_ENST00000303562     -1.905499e-11
KLF6_ENST00000542957    -1.883375e-11
PLSCR1_ENST00000342435  -1.876881e-11
MSC_ENST00000325509     -1.837029e-11
BATF_ENST00000286639    -1.824286e-11
STAT6_ENST00000300134   -1.468517e-11
NFKB1_ENST00000652569   -1.461949e-11
IRF1_ENST00000405885    -1.433633e-11
CEBPB_ENST00000303004   -1.358728e-11
LYL1_ENST00000264824    -1.207118e-11
ZNF385A_ENST00000394313 -1.192159e-11
MBD2_ENST00000256429    -1.162222e-11
KLF6_ENST00000497571    -1.154590e-11
BHLHE40_ENST00000256495 -1.153686e-11

In [18]:
unbalanced_monocyte = node_light_up("unbalanced_4_class",transcript_ID,expression,"Monocyte")

/state/partition1/job-4470344/ipykernel_724939/1994595373.py:11: Pandas4Warning: Starting with pandas version 4.0 all arguments of mean will be keyword-only.
  tf_data = pd.DataFrame(express_mat).iloc[:,:].mean(1)

411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [19]:
unbalanced_monocyte.head(n=20)

                         Monocyte
YBX1_ENST00000467957    -0.184648
YBX1_ENST00000436427    -0.180192
ZNF706_ENST00000517844  -0.154406
NR1H3_ENST00000441012   -0.151993
CEBPD_ENST00000408965   -0.142018
ATF3_ENST00000341491    -0.133511
ZNF706_ENST00000519744  -0.127110
MSC_ENST00000325509     -0.106240
JUN_ENST00000678696     -0.100035
TSC22D1_ENST00000261489 -0.099088
HMGA1_ENST00000311487   -0.095725
NR1H3_ENST00000494018   -0.087400
SPI1_ENST00000227163    -0.086923
GLMP_ENST00000362007    -0.084164
BHLHE40_ENST00000256495 -0.083581
ETV5_ENST00000306376    -0.077505
BHLHE41_ENST00000242728 -0.075012
NFE2L2_ENST00000397062  -0.074717
USF2_ENST00000599625    -0.074068
MAFB_ENST00000373313    -0.073354

In [20]:
for idx, t in enumerate(unbalanced_monocyte.index):
    if "ZNF385A" in str(t):
        print(idx)

48
89
153
875
1247
2364
4109
10333
10708
10949
11001
12588
12777
12888
12996

In [21]:
unbalanced_other = node_light_up("unbalanced_4_class",transcript_ID,expression,"other")

/state/partition1/job-4470344/ipykernel_724939/1994595373.py:11: Pandas4Warning: Starting with pandas version 4.0 all arguments of mean will be keyword-only.
  tf_data = pd.DataFrame(express_mat).iloc[:,:].mean(1)

411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [22]:
unbalanced_other.head(n=20)

                                other
YBX1_ENST00000436427    -5.260964e-07
CEBPD_ENST00000408965   -3.520194e-07
YBX1_ENST00000467957    -3.264876e-07
SPI1_ENST00000227163    -3.222357e-07
HMGA1_ENST00000311487   -3.011820e-07
MSC_ENST00000325509     -2.980084e-07
MAFB_ENST00000373313    -2.824736e-07
FOS_ENST00000303562     -2.173225e-07
NR1H3_ENST00000441012   -2.154600e-07
ZNF706_ENST00000519744  -1.969321e-07
NFE2L2_ENST00000397062  -1.693817e-07
ATF3_ENST00000341491    -1.621826e-07
GLMP_ENST00000362007    -1.580171e-07
ZNF706_ENST00000517844  -1.512270e-07
IRF1_ENST00000405885    -1.502667e-07
FOS_ENST00000555686     -1.455924e-07
PLSCR1_ENST00000342435  -1.272836e-07
BHLHE40_ENST00000256495 -1.272496e-07
STAT1_ENST00000392322   -1.270866e-07
ZEB2_ENST00000409487    -1.260665e-07

In [23]:
for idx, t in enumerate(unbalanced_other.index):
    if "ZNF385A" in str(t):
        print(idx)

20
74
204
292
1182
1379
3248
11517
11666
11905
11913
12064
12638
12879
12979

In [45]:
ROS_macrophages = node_light_up("ROS_4_class",transcript_ID,expression,"Macrophage")

/state/partition1/job-4454411/ipykernel_873094/1994595373.py:11: Pandas4Warning: Starting with pandas version 4.0 all arguments of mean will be keyword-only.
  tf_data = pd.DataFrame(express_mat).iloc[:,:].mean(1)

411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [46]:
ROS_macrophages.head(n=20)

                        Macrophage
FOS_ENST00000303562      -0.000005
MAFB_ENST00000373313     -0.000004
JUNB_ENST00000302754     -0.000004
KLF6_ENST00000542957     -0.000004
KMT2A_ENST00000648029    -0.000003
YBX1_ENST00000332220     -0.000003
XBP1_ENST00000216037     -0.000003
STAT6_ENST00000300134    -0.000003
KLF6_ENST00000497571     -0.000003
FOS_ENST00000556324      -0.000002
DRAP1_ENST00000312515    -0.000002
ATF4_ENST00000674920     -0.000002
KLF10_ENST00000285407    -0.000002
IRF1_ENST00000679700     -0.000002
ETS2_ENST00000360938     -0.000002
USF2_ENST00000222305     -0.000002
NFE2L2_ENST00000699431   -0.000002
MXD1_ENST00000465446     -0.000002
MXD1_ENST00000264444     -0.000002
AHR_ENST00000242057      -0.000001

In [47]:
ROS_microglia = node_light_up("ROS_4_class",transcript_ID,expression,"Microglia")

/state/partition1/job-4454411/ipykernel_873094/1994595373.py:11: Pandas4Warning: Starting with pandas version 4.0 all arguments of mean will be keyword-only.
  tf_data = pd.DataFrame(express_mat).iloc[:,:].mean(1)

411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [48]:
ROS_microglia.head(n=20) # doubling

                           Microglia
MAFB_ENST00000373313   -2.770355e-15
FOS_ENST00000303562    -2.722074e-15
XBP1_ENST00000216037   -2.563653e-15
KLF6_ENST00000497571   -2.372188e-15
KLF6_ENST00000542957   -2.329895e-15
MSC_ENST00000325509    -2.242758e-15
STAT6_ENST00000300134  -2.232001e-15
YBX1_ENST00000332220   -1.719414e-15
PLSCR1_ENST00000342435 -1.683094e-15
KMT2A_ENST00000648029  -1.677730e-15
MXD1_ENST00000465446   -1.579929e-15
JUNB_ENST00000302754   -1.533476e-15
AHR_ENST00000242057    -1.362317e-15
YBX1_ENST00000436427   -1.304561e-15
KLF4_ENST00000497048   -1.300606e-15
MXD1_ENST00000264444   -1.300453e-15
KLF10_ENST00000285407  -1.280288e-15
DRAP1_ENST00000312515  -1.247363e-15
FOS_ENST00000556324    -1.242389e-15
BATF_ENST00000286639   -1.232340e-15

In [49]:
SMOTE_macrophages = node_light_up("SMOTE_4_class",transcript_ID,expression,"Macrophage")

/state/partition1/job-4454411/ipykernel_873094/1994595373.py:11: Pandas4Warning: Starting with pandas version 4.0 all arguments of mean will be keyword-only.
  tf_data = pd.DataFrame(express_mat).iloc[:,:].mean(1)

411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [50]:
SMOTE_macrophages.head(n=20)

                       Macrophage
KLF6_ENST00000542957    -0.024114
FOS_ENST00000303562     -0.016860
ATF4_ENST00000674920    -0.012609
KMT2A_ENST00000648029   -0.012375
STAT6_ENST00000300134   -0.009320
XBP1_ENST00000216037    -0.008497
YBX1_ENST00000321358    -0.007506
USF2_ENST00000222305    -0.006612
NFKB1_ENST00000652569   -0.005780
SPI1_ENST00000378538    -0.005556
CEBPB_ENST00000303004   -0.005097
KLF10_ENST00000285407   -0.004685
FOSL2_ENST00000264716   -0.004662
MXD1_ENST00000465446    -0.004527
LYL1_ENST00000264824    -0.004014
HES1_ENST00000476918    -0.003554
KLF4_ENST00000497048    -0.003552
ATF4_ENST00000337304    -0.003396
MBD2_ENST00000256429    -0.003153
FOS_ENST00000556324     -0.003060

In [51]:
SMOTE_microglia = node_light_up("SMOTE_4_class",transcript_ID,expression,"Microglia")

/state/partition1/job-4454411/ipykernel_873094/1994595373.py:11: Pandas4Warning: Starting with pandas version 4.0 all arguments of mean will be keyword-only.
  tf_data = pd.DataFrame(express_mat).iloc[:,:].mean(1)

411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [52]:
SMOTE_microglia.head(n=20)

                            Microglia
YBX1_ENST00000436427    -2.026894e-08
MSC_ENST00000325509     -8.206555e-09
CEBPD_ENST00000408965   -6.377741e-09
JUNB_ENST00000302754    -5.279803e-09
YBX1_ENST00000467957    -4.491543e-09
HMGA1_ENST00000311487   -4.341952e-09
NFE2L2_ENST00000397062  -4.326965e-09
PLSCR1_ENST00000342435  -4.016025e-09
ZNF706_ENST00000519744  -3.534767e-09
EGR2_ENST00000242480    -3.116971e-09
PIN1_ENST00000247970    -3.062112e-09
ZNF385A_ENST00000394313 -3.032639e-09
HMGN3_ENST00000344726   -2.851671e-09
BATF_ENST00000286639    -2.775653e-09
FOS_ENST00000555686     -2.727673e-09
NFKB2_ENST00000697884   -2.471330e-09
ZNF302_ENST00000507959  -2.449346e-09
ZNF706_ENST00000517844  -2.267020e-09
ATF3_ENST00000613104    -2.184023e-09
ATF3_ENST00000336937    -2.143057e-09

In [53]:
BLSMOTE_macrophages = node_light_up("BLSMOTE_4_class",transcript_ID,expression,"Macrophage")

/state/partition1/job-4454411/ipykernel_873094/1994595373.py:11: Pandas4Warning: Starting with pandas version 4.0 all arguments of mean will be keyword-only.
  tf_data = pd.DataFrame(express_mat).iloc[:,:].mean(1)

411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [54]:
BLSMOTE_macrophages.head(n=20)

                        Macrophage
KMT2A_ENST00000648029    -0.413059
KLF6_ENST00000542957     -0.410554
SPI1_ENST00000378538     -0.405318
YBX1_ENST00000332220     -0.335987
STAT6_ENST00000300134    -0.317484
CEBPB_ENST00000303004    -0.282957
YBX1_ENST00000321358     -0.278203
MAFB_ENST00000373313     -0.269215
NFKB1_ENST00000652569    -0.237489
ATF4_ENST00000674920     -0.221919
FOS_ENST00000303562      -0.218832
FOS_ENST00000556324      -0.218259
USF2_ENST00000222305     -0.215238
FOS_ENST00000554617      -0.195065
IRF1_ENST00000679700     -0.187496
KLF4_ENST00000497048     -0.182797
KLF10_ENST00000285407    -0.170828
XBP1_ENST00000216037     -0.169058
CSRNP1_ENST00000273153   -0.166307
SON_ENST00000475072      -0.159332

In [55]:
BLSMOTE_microglia = node_light_up("BLSMOTE_4_class",transcript_ID,expression,"Microglia")

/state/partition1/job-4454411/ipykernel_873094/1994595373.py:11: Pandas4Warning: Starting with pandas version 4.0 all arguments of mean will be keyword-only.
  tf_data = pd.DataFrame(express_mat).iloc[:,:].mean(1)

411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
411/411 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [56]:
BLSMOTE_microglia.head(n=20)

                            Microglia
YBX1_ENST00000436427    -1.340101e-07
MSC_ENST00000325509     -6.143340e-08
YBX1_ENST00000467957    -5.877298e-08
CEBPD_ENST00000408965   -4.634818e-08
NR1H3_ENST00000441012   -4.275080e-08
ZNF706_ENST00000517844  -3.876193e-08
IRF1_ENST00000405885    -3.841902e-08
ZNF706_ENST00000519744  -3.813847e-08
HMGA1_ENST00000311487   -3.758130e-08
ZNF385A_ENST00000394313 -2.923500e-08
BATF_ENST00000286639    -2.919056e-08
JUN_ENST00000678696     -2.729530e-08
GLMP_ENST00000362007    -2.639136e-08
BCL6_ENST00000406870    -2.559520e-08
HMGN3_ENST00000344726   -2.500920e-08
PLSCR1_ENST00000342435  -2.465277e-08
FOS_ENST00000555686     -2.425580e-08
ATF3_ENST00000336937    -2.371233e-08
JUN_ENST00000371222     -2.361624e-08
PHF19_ENST00000312189   -2.122755e-08